### DISCUSSION TITLE
favicon for Argus UI

### DISCUSSION THREAD

**Discussion by ruslan-mogilevskiy** [release-argus/Argus#353] [Q&A] [answered]
Is there a way to specify an icon URL for Argus UI itself in the Argus config?

**Comment by JosephKav** [comment, marked as answer]
I could quite easily add support for something like this if you'd like?
```yaml
settings:
  web:
    favicon:
      svg: URL # override /favicon.svg
      png: URL # override /apple-touch-icon.png
```
As the favicon is what renders as the icon in the top left of the UI, this would also change that.

If you have a better favicon for Argus that you want to share, I'm very open to changing Argus' icon :)

---
Added support for the above yaml in #355
