### DISCUSSION TITLE
Service - Sonarr Nightly

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#36] [Show and tell]
```yaml
  Sonarr/Sonarr:
    type: url
    url: http://services.sonarr.tv/v1/releases
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: \"version\":\s?\"([0-9.]+)\"
        index: 1
    web_url: http://ip_addresss:port/base_url/system/updates
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/sonarr.png
    deployed_version:
      url: http://ip_addresss:port/base_url/api/v3/system/status?apikey=your_apikkey_here
      json: version
```

**Comment by JosephKav** [comment]
Glad we figured out your [issue](https://github.com/release-argus/Argus/issues/34) with positive look behinds for getting the nightly Sonarr release here. Just an fyi in case you missed it as I did add it when I edited my post a bit later after posting, but you can greatly shorten the second query as it would only be checking the results of the query before it, so it's doing very large regex on just `"version":"1.2.3.4"`
You could shorten the second url_command to just
```yaml
      - type: regex_submatch
        regex: ([0-9.]+)
```
or
```yaml
      - type: regex
        regex: '[0-9.]+'
        index: 0
```
(And those brackets in your first command do nothing. The match part is only used in `regex_submatch`}
