### DISCUSSION TITLE
Service - Radarr Nightly

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#37] [Show and tell]
```yaml
  Radarr/Radarr:
    type: url
    url: https://radarr.servarr.com/v1/update/nightly/changes?runtime=netcore&os=linuxmusl
    semantic_versioning: false
    url_commands:
      - type: regex_submatch
        regex: \"version\":\"([0-9.]+)\"
    web_url: http://ip_addresss:port/base_url/system/updates
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/radarr.png
    deployed_version:
      url: http://ip_addresss:port/base_url/api/v3/system/status?apikey=your_apikkey_here
      json: version
```
