### DISCUSSION TITLE
Service - Readarr Nightly

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#39] [Show and tell]
```yaml
  Readarr/Readarr:
    type: url
    url: https://readarr.servarr.com/v1/update/nightly/changes?runtime=netcore&os=linuxmusl
    semantic_versioning: false
    url_commands:
      - type: regex_submatch
        regex: \"version\":\"([0-9.]+)\"
    web_url: http://ip_addresss:port/base_url/system/updates
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/readarr.png
    deployed_version:
      url: http://ip_addresss:port/base_url/api/v1/system/status?apikey=your_apikey_here
      json: version
```
