### DISCUSSION TITLE
Service - Amir20/Dozzle Latest

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#40] [Show and tell]
```yaml
  Amir20/Dozzle:
    type: github
    url: amir20/dozzle
    url_commands:
      - type: regex_submatch
        regex: v([0-9.]+)$
    web_url: https://github.com/amir20/dozzle/releases/releases/v{{ version }}
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/dozzle.png
    deployed_version:
      url: http://ip_addresss:port/base_url/settings
      \"version\":\s?\"v([0-9.]+)\"
```
