### DISCUSSION TITLE
Service - SABnzbd latest

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#43] [Show and tell]
```
  SABnzbd/SABnzbd:
    type: github
    url: SABnzbd/SABnzbd
    semantic_versioning: false
    url_commands:
      - type: regex_submatch
        regex: ([0-9a-z.]+)$
    web_url: https://github.com/sabnzbd/sabnzbd/releases/tag/{{ version }}
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/sabnzbd.png
    deployed_version:
      url: http://ip_address:port/base_url/api?apikey=your_apikkey_here&status&output=josn&mode=queue
      regex: version':\s?'([0-9.]+)',
```
