### DISCUSSION TITLE
Service LSIO/Plex Latest (with PlexPass)

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#48] [Show and tell]
```
  LSIO/Plex:
    type: url
    url: https://www.reddit.com/r/PleX/search/?q=%22New%20BETA%20PMS%20Version%20Available%22&restrict_sr=1&sr_nsfw=&t=month&sort=new
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: New\sBETA\sPMS\sVersion\sAvailable\s\-\s([0-9a-z\-.]+)
        index: 0
      - type: regex_submatch
        regex: \-\s([0-9a-z-.]+)
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/plex.png
    deployed_version:
      url: http://ip_address:32400/?X-Plex-Token=plex_token_here
      regex: updater=\"1\" version=\"([0-9a-z\-.]+)\"
```
