### DISCUSSION TITLE
Service - LSIO/Bazarr latest

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#49] [Show and tell]
```
  Bazarr/Bazarr:
    type: url
    url: https://api.github.com/repos/morpheus65535/bazarr/releases/latest
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: \"name\":\s?\"v([0-9.]+)\"
    web_url: http://ip_addresss:port/base_url/system/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/bazarr.png
    deployed_version:
      url: http://ip_addresss:port/base_url/api/system/status?apikey=your_apikkey_here
      regex: \"bazarr_version\":\s\"([0-9.]+)\"
```
