### DISCUSSION TITLE
Service - Dgtlmoon/Changedetection.io

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#51] [Show and tell]
```
  dgtlmoon/changedetection.io:
    type: url
    url: https://github.com/dgtlmoon/changedetection.io/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/([0-9.]+)
    web_url: https://github.com/dgtlmoon/changedetection.io/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/changedetection-io.png
    deployed_version:
      url: http://ip_addresss:port/
      regex: sticky\"\>v([0-9.]+)\<\/div\>
```
