### DISCUSSION TITLE
Use default notify for all services

### DISCUSSION THREAD

**Discussion by BornTKill** [release-argus/Argus#512] [Q&A] [answered]
Dear,

Thank you for this very nice project.
I have this default configuration like this;

```
defaults:
  service:
    options:
      interval: 10m
    latest_version:
      access_token: <secret>
    deployed_version:
      allow_invalid_certs: true
  notify:
    SLACK_NOTIFY:
      type: slack
      url_fields:
        channel: release-argus
        token: <secret>
```

Not sure how to use SLACK_NOTIFY by default for all my services.
Thank you.

**Comment by JosephKav** [comment, marked as answer]
You'll need to indent it once more so that the notify is under the service.

`defaults.notify` is where you can set defaults for your notifier types (e.g. `defaults.notify.slack`, or `defailts.notify.gotify`). To set the defaults for a service, you set `defaults.service.notify`.

```yaml
defaults:
  service:
    options:
      interval: 10m
    latest_version:
      access_token: <secret>
    deployed_version:
      allow_invalid_certs: true
    notify:
      SLACK_NOTIFY:
        type: slack
        url_fields:
          channel: release-argus
          token: <secret>
```

**Comment by tonyctalope** [comment]
This is what is working for me now : 
```yml
notify:
  SLACK_NOTIFY:
    type: slack
    url_fields:
      channel: release-argus
      token: <secret>
defaults:
  service:
    options:
      interval: 10m
    latest_version:
      access_token: <secret>
    deployed_version:
      allow_invalid_certs: true
    notify:
      SLACK_NOTIFY: {}
```
