### DISCUSSION TITLE
Service - Cadvisor

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#53] [Show and tell]
```
  Cadvisor:
    type: url
    url: https://github.com/google/cadvisor/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/v([0-9.]+)
    web_url: https://github.com/google/cadvisor/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/cadvisor.png
    deployed_version:
      url: http://ip_addressr:port/base_url/metrics
      regex: cadvisorVersion=\"v([0-9.]+)\"
```
