### DISCUSSION TITLE
EMS-ESP32 deployed version

### DISCUSSION THREAD

**Discussion by wardwygaerts** [release-argus/Argus#532] [Q&A] [answered]
I'm trying to get the installed version of [EMS-ESP32](https://github.com/emsesp/EMS-ESP32), but I don't get it to work.

When I go to the System Status page of my EMs instance, I see the below rest call:
![image](https://github.com/user-attachments/assets/88698365-6e79-4286-a26c-8727fa159928)

With this response
```
{
    "emsesp_version": "3.6.2",
    "esp_platform": "ESP32",
    "cpu_freq_mhz": 240,
    "max_alloc_heap": 75,
    "free_heap": 147,
    "sdk_version": "4.4.5.230901",
    "flash_chip_size": 4096,
    "flash_chip_speed": 40000000,
    "app_used": 1547,
    "app_free": 437,
    "fs_used": 28,
    "fs_free": 36,
    "uptime": "000+04:12:54.177",
    "has_loader": false
}
```

So how can I get this to work with the Bearer token?

**Comment by JosephKav** [comment, marked as answer]
Hi. This should be quite simple to add to Argus. Try this:
![image](https://github.com/user-attachments/assets/a94edb7f-5b8c-4cf9-adcf-dadf6bd9f795)


How long that will work for depends on whether there's an expiration tied to that bearer token

**Comment by wardwygaerts** [comment]
Thanks! You can grab the token in the settings part of the user which is used, so it remains the same.

```
EMS-ESP32:
    latest_version:
      type: github
      url: emsesp/EMS-ESP32
      access_token: <secret>
    deployed_version:
      method: GET
      url: http://x.x.x.x/rest/systemStatus
      headers:
        - key: Authorization
          value: Bearer <token>
      json: emsesp_version
    dashboard:
      icon: https://avatars.githubusercontent.com/u/59766360?s=200&v=4
      icon_link_to: http://x.x.x.x
      web_url: https://github.com/emsesp/EMS-ESP32/releases
```
