### DISCUSSION TITLE
Getting failed converting JSON - unexpected end of JSON input for linuxserver/docker-projectsend

### DISCUSSION THREAD

**Discussion by mstewart14** [release-argus/Argus#534] [Q&A]
Not sure what to do with this, any help would be appreciated.

**Comment by JosephKav** [comment]
Happy to help.
What URLs are you using and what do their responses look like?

**Reply by mstewart14** [reply]
current setting is 
```
  projectsend:
    comment: service for sharing files with clients
    options:
      interval: 24h
      semantic_versioning: false
    latest_version:
      type: url
      url: https://www.projectsend.org/
      url_commands:
        - type: regex
          regex: (?:Download version ).([0-9]\d*)
    dashboard:
      icon: https://<mydomain>/favicon.ico
      icon_link_to: https://hub.docker.com/r/linuxserver/projectsend
      web_url: https://<mydomain>
```

This returns 1720 which isn't great but it's better than nothing.
There doesn't appear to be an api or anything in the deployed version where I can find the version but I'm living with it...

If I change this to type: github and linuxserver/docker-projectsend
the only thing I get back is the error I posted here.

**Reply by mstewart14** [reply]
sigh... solved it myself... 
```  
projectsend:
    comment: service for sharing files with clients
    options:
      interval: 24h
      semantic_versioning: false
    latest_version:
      type: url
      url: https://github.com/linuxserver/docker-projectsend/releases
      url_commands:
        - type: regex
          regex: r[0-9]\d*-ls[0-9]\d*
```
