### DISCUSSION TITLE
Service - Nginx-Proxy-Manager

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#54] [Show and tell]
```
  Nginx-Proxy-Manager:
    type: url
    url: https://github.com/NginxProxyManager/nginx-proxy-manager/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/v([0-9.]+)
    web_url: https://github.com/NginxProxyManager/nginx-proxy-manager/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/nginxproxymanager.png
    deployed_version:
      url: http://ip_address:port/login
      regex: data-version=\"([0-9.]+)\"
```
