### DISCUSSION TITLE
Getting deployed_version howto

### DISCUSSION THREAD

**Discussion by 123mariachi123** [release-argus/Argus#541] [General]
First of all let me say that this is a great project! Thanks for all your efforts.

However, i fail in understanding how i can get the version number of my deployed versions. 
Fortunately the docs already cover a lot of services that i am using but not e.g.
- https://github.com/gethomepage/homepage
- https://github.com/nzbgetcom/nzbget
- https://github.com/fallenbagel/jellyseerr or
- https://github.com/schlagmichdoch/PairDrop

just to mention 4 of them.

Can anyone guide me and tell me how to get the version number in general? Is there a certain approach that you usually follow?
In all software i can browse to a page where i can find the version but trying to use regex to extract it from that page fails.

How do you usually approach this? How can i find out if e.g. a path like .../health or .../about or .../api/... exist and i can access the information?

Thanks a lot for your help and keep the good work going 😄

**Comment by JosephKav** [comment]
Hi, glad you're liking it :)

To get the deployed versions, I'd normally go to my deployed instance and see if the version is displayed anywhere. Then open the network tab in my browser and find where it's going to get that data. Or I'd try searching for a list of api endpoints on the GitHub page

**Reply by 123mariachi123** [reply]
Alright, this was already helpful, although i am really bad when it comes to web related stuff 😫 

Concerning my 4 examples above i was able to solve 2 so far with your hint and a bit of luck. 
Just in case anyone has the same issue or you want to add it to your docs:

### Jellyseerr
``` yml
  fallenbagel/jellyseerr:
    latest_version:
      type: github
      url: fallenbagel/jellyseerr
      url_commands:
        - type: regex
          regex: v([0-9.]+)$
    deployed_version:
      method: GET
      url: https://jellyseerr.example.io/api/v1/status
      json: version
    dashboard:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyseerr.png
      web_url: https://github.com/fallenbagel/jellyseerr/releases/v{{ version }}
```

### NZBget (i am no fan of services that require authentication just to get the version number though)
```yml
  fnzbgetcom/nzbget:
    options:
      semantic_versioning: false
    latest_version:
      type: github
      url: nzbgetcom/nzbget
      url_commands:
        - type: regex
          regex: v([0-9.]+)$
    deployed_version:
      method: GET
      url: https://nzbget.example.io/jsonrpc/version
      basic_auth:
        username: <username>
        password: <password>
      json: result
      regex: v([0-9.]+)$
    dashboard:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nzbget.png
      web_url: https://github.com/nzbgetcom/nzbget/releases/v{{ version }}
```

Still struggling with PairDrop and Homepage though. I am open for ideas 😄
