### DISCUSSION TITLE
Service - AdguardHome

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#65] [Show and tell]
Requires authentication disabled in AdGuard Home

```
  AdguardHome:
    type: github
    url: AdguardTeam/AdGuardHome
    semantic_versioning: false
    web_url: https://github.com/AdguardTeam/AdGuardHome/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/adguard-home.png
    deployed_version:
      url: http://ip_address:port/control/status
      json: version
```
