### DISCUSSION TITLE
Service - Caddy

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#66] [Show and tell]
This one requires a script to get the current versions deployed and write them to a text file that Argus then reads from.  The srcipt is run every 30 mins via cron.  The file is served by Caddy.

current_verson.sh
```
#!/bin/bash
cd /home/users/Documents/Docker/caddy2
docker exec caddy /bin/sh -c "caddy list-modules -versions | grep caddy.adapters" 2>&1 > current_version.txt
docker exec caddy /bin/sh -c "caddy list-modules -versions | grep security" 2>&1 >> current_version.txt
docker exec caddy /bin/sh -c "caddy list-modules -versions | grep trace" 2>&1 >> current_version.txt
docker exec caddy /bin/sh -c "caddy list-modules -versions | grep realip" 2>&1 >> current_version.txt
docker exec caddy /bin/sh -c "caddy build-info | grep proxy" 2>&1 >> current_version.txt
chmod 777 current_version.txt
chown 1000:1000 current_version.txt
```

```
   Caddy:
    type: url
    url: https://github.com/caddyserver/caddy/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/caddyserver/caddy/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    deployed_version:
      url: http://ip_address:port/caddy2/current_version.txt
      regex: caddy.adapters.caddyfile\s?(v[0-9.]+)
  CaddyDockerProxy:
    type: url
    url: https://github.com/lucaslorentz/caddy-docker-proxy/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/lucaslorentz/caddy-docker-proxy/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    deployed_version:
      url: http://ip_address:port/caddy2/current_version.txt
      regex: caddy-docker-proxy/v2\s?(v[0-9.]+)
  CaddyRealIP:
    type: url
    url: https://github.com/kirsch33/realip/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/kirsch33/realip/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    deployed_version:
      url: http://ip_address:port/caddy2/current_version.txt
      regex: realip\s?(v[0-9.]+)
  CaddySecurity:
    type: url
    url: https://github.com/greenpau/caddy-security/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/greenpau/caddy-security/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    deployed_version:
      url: http://ip_address:port/caddy2/current_version.txt
      regex: security\s?(v[0-9.]+)
  CaddyTrace:
    type: url
    url: https://github.com/greenpau/caddy-trace/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/greenpau/caddy-trace/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    deployed_version:
      url: http://ip_address:port/caddy2/current_version.txt
      regex: trace\s?(v[0-9.]+)
```
