### DISCUSSION TITLE
Service - FileBrowser

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#67] [Show and tell]
Disable auth first in filebrowser.json

**filebrowser.json**
```
{
  "port": 8090,
  "baseURL": "/filebrowser",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv",
  "noauth": true
}
```
**Argus Service Definition**
```
  FileBrowser:
    type: github
    url: filebrowser/filebrowser
    url_commands:
      - type: regex
        regex: v([0-9.]+)$
    web_url: https://github.com/filebrowser/filebrowser/releases/v{{ version }}
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/filebrowser.png
    gotify:
      GOTIFY_NOTIFICATION: {}
    deployed_version:
      url: http://ip_address:port/base_url/files/
      regex: \"Version\":\s?\"([0-9.]+)\"
```
