### DISCUSSION TITLE
Service - Portainer

### DISCUSSION THREAD

**Discussion by samcro1967** [release-argus/Argus#68] [Show and tell]
```
  Portainer:
    type: github
    url: portainer/portainer
    url_commands:
      - type: regex
        regex: ([0-9.]+)$
    web_url: https://github.com/portainer/portainer/releases/{{ version }}
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/portainer.png
    gotify:
      GOTIFY_NOTIFICATION: {}
    deployed_version:
      url: http://ip_address:port/api/status
      regex: \"Version\":\s?\"([0-9.]+)\"
```
