### ISSUE TITLE
Notify param Jinja templating (var expansion)

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#100]
When I receive an smtp notification, the variables are not being expanded.  It works in Discord and Gotify.  Not sure if I don't have the config quite right or maybe variables are not supported for the subject line?

**Global config**
```
  MAILRISE_NOTIFICATION:
    type: smtp
    url_fields:
      host: 192.168.1.104
      port: "8025"
    params:
      auth: None
      fromaddress: argus@mydomain.net
      fromname: Argus
      subject: '{{ service_id }} - {{ version }} released.'
      toaddresses: argus@osuhickeys.net
      usehtml: "no"
      usestarttls: "no"
```
**Image of email**
![image](https://user-images.githubusercontent.com/2319445/175122280-5b2203c1-44a2-456d-a62e-b4b036660504.png)
