### ISSUE TITLE
feat: command to check version validity

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#111]
Like we have `regex_content` to require content regex to match on the page before we consider a release valid, this will add support for any `command` to be run to determine whether the release is valid.

e.g.
```yaml
service:
  release-argus/Argus:
    type: github
    url: release-argus/Argus
    require:
      command: ["bash", "check_for_docker_upgrade", "{{ service_id }}"]
```
Then that script would check the current and latest sha for service_id and return status code 1 if they're the same.

_Originally posted by @JosephKav in https://github.com/release-argus/Argus/issues/102#issuecomment-1171224002_
