### ISSUE TITLE
feat: check for docker tag before release is considered usable

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#112]
e.g.
```yaml
service:
  argus:
    latest_version:
      type: github
      url: release-argus/argus
      require:
        docker:
          type: docker/quay/ghcr
          repo: argus-io/argus
          token: TOKEN
          tag: '{{ version }}' # tag style of the docker image
```

Then this'll check for the existance of the tag at
Docker:
`https://index.docker.io/v1/repositories/releaseargus/argus/tags/{{ version }}`
Quay:
`curl --header 'Authorization: Bearer TOKEN' https://quay.io/api/v1/repository/argus-io/argus`
map to json and see if `{{ version }}` is a key
GHCR:
`https://api.github.com/repos/release-argus/Argus/tags`

_Originally posted by @JosephKav in https://github.com/release-argus/Argus/issues/102#issuecomment-1171193382_
