### ISSUE TITLE
Plex RegEx not working after upgrading to 0.9.0

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#142]
I noticed that Plex is reporting no successful queries after upgrading to 0.9.0.  I am grabbing the latest version from this [link](https://www.reddit.com/r/PleX/search/?q=%22New%20BETA%20PMS%20Version%20Available%22&restrict_sr=1&sr_nsfw=&t=month&sort=new) and using `New\sBETA\sPMS\sVersion\sAvailable\s\-\s([0-9a-z\-.]+)` as the RegEx match.  The RegEx works at https://regoio.herokuapp.com and the same RegEx match works for the deployed version.  From what I can tell link I am grabbing the latest version from has not changed.  From what I can tell in the logs, it seems like everything is being parsed properly form the config file.  Scratching my head on this one.

**Logs**
```
2022/08/11 14:06:10 INFO: Testing (Plex),
2022/08/11 14:06:10 WARNING: Plex (url_commands), regex "New\\sBETA\\sPMS\\sVersion\\sAvailable\\s\\-\\s([0-9a-z\\-.]+)" didn't return any matches
2022/08/11 14:06:10 ERROR: Testing (Plex), No version matching the conditions specified could be found for "Plex" at "https://www.reddit.com/r/PleX/search/?q=%22New%20BETA%20PMS%20Version%20Available%22&restrict_sr=1&sr_nsfw=&t=month&sort=new"

2022/08/11 14:06:10 INFO: Testing (Plex), Deployed version - "1.28.1.6041-738907df3"
```

<details>
  <summary>Config.yml</summary>

```
  Plex:
    options:
      semantic_versioning: false
      comment: New\sBETA\sPMS\sVersion\sAvailable\s\-\s([0-9a-z\-.]+)
    latest_version:
      type: url
      url: https://www.reddit.com/r/PleX/search/?q=%22New%20BETA%20PMS%20Version%20Available%22&restrict_sr=1&sr_nsfw=&t=month&sort=new
      url_commands:
        - type: regex
          regex: New\sBETA\sPMS\sVersion\sAvailable\s\-\s([0-9a-z\-.]+)
    deployed_version:
      url: http://osu.plex:32400/?X-Plex-Token=<redacted>
      regex: updater=\"1\" version=\"([0-9a-z\-.]+)\"
    notify:
      MAILRISE_NOTIFICATION: {}
    webhook:
      WEBHOOK_DRONE_BUILD:
        url: http://192.168.1.104:9358/hooks/build_docker?container=plex
    dashboard:
      auto_approve: true
      icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/plex.png
      icon_link_to: http://osu.plex:32400/web/
```
</details>
