### ISSUE TITLE
Docker Tag Usage Error Logging

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#146]
Working on setting up a Docker tag check another application.  I am somewhat confused by the error in the log.  If I do not have the require block in, the check works as expected.  If I add the block, the logs show `ERROR: Testing (Ombi), No version matching the conditions specified could be found for "Ombi" at "https://github.com/Ombi-app/Ombi/releases"`.  I know that is not the case as it works without the require block.  Guessing the check that is failing is really against `https://hub.docker.com/r/linuxserver/ombi/tags`???

<summary>config.yml</summary>

<details>

```
  Ombi:
    options:
      semantic_versioning: false
    latest_version:
      type: url
      url: https://github.com/Ombi-app/Ombi/releases
      use_prerelease: true
      url_commands:
        - type: regex
          regex: releases\/tag\/v([0-9.]+)
      require:
        regex_content: 'amd64-development-version-v{{ version }}'
        regex_version: ([0-9.]+)$ 
        docker:
          type: hub
          image: linuxserver/ombi
          tag: v{{ version }}
    deployed_version:
      url: http://osu.ombi:3579/ombi/api/v1/Settings/about?apikey=<redacted>
      json: version
    notify:
      MAILRISE_NOTIFICATION: {}
    webhook:
      WEBHOOK_DRONE_BUILD:
        url: http://192.168.1.104:9358/hooks/build_docker?container=ombi
    dashboard:
      auto_approve: true
      icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/ombi.png
      icon_link_to: http://osu.ombi:3579/ombi
      web_url: https://github.com/Ombi-app/Ombi/releases
```
</details>

**Comment by JosephKav** [comment]
Looking quickly, it appears that Argus would find the version of `4.24.0` from your regex. Then it looks for a tag of `v4.24.0` on `linuxserver/ombi`, but that tag doesn't exist (The closest I see is `development-version-v4.24.0`), so the conditions didn't match, so it doesn't find a version

**Comment by samcro1967** [comment]
So switching the require block to the below solved it.  I guess I am not clear on what the usage of regex_content & regex_version is in the require block.

```
      require:
        docker:
          type: hub
          image: linuxserver/ombi
          tag: 'amd64-development-version-v{{ version }}'
```
