### ISSUE TITLE
bug: Service type URL return wrong tag as newest version

### ISSUE THREAD

**Issue by larsl-net** [release-argus/Argus#149]
**Describe the bug**
To track the version from my GitLab I use a Service with the type url.
Argus find the latest version `15.1.5-ee` but the right version is `15.3.1-ee`

`WARNING: gitlab-org/gitlab, queried version "15.1.5-ee" is less than the deployed version "15.3.1-ee"`

When I use curl and grep to check wich versions are found with the API call I get the following result.
```bash
$ curl -s https://gitlab.com/api/v4/projects/278964/repository/tags | grep -oP '\"name\":\"v([0-9.]+\-ee)\"'
"name":"v15.1.5-ee"
"name":"v15.2.3-ee"
"name":"v15.3.1-ee"
"name":"v15.3.0-ee"
"name":"v15.2.2-ee"
"name":"v15.0.5-ee"
"name":"v15.1.4-ee"
"name":"v15.2.1-ee"
"name":"v15.2.0-ee"
"name":"v15.1.3-ee"
"name":"v15.1.2-ee"
"name":"v14.10.5-ee"
"name":"v15.0.4-ee"
"name":"v15.1.1-ee"
"name":"v15.1.0-ee
```

**To Reproduce**
Use the following Config (`devpoyed_version` removed, becaus of API Token):
```yaml
service:
  gitlab-org/gitlab:
    latest_version:
      type: url
      url: https://gitlab.com/api/v4/projects/278964/repository/tags
      url_commands:
        - type: regex
          regex: \"name\":\"v([0-9.]+\-ee)"
    dashboard:
      icon: https://gitlab.com/gitlab-org/gitlab/-/raw/master/public/slash-command-logo.png
      web_url: https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG.md
```

**Expected behavior**
The right latest version is found (current: `15.3.1-ee`).

**Additional context**
Same problem as in #10 only with type `url` instead of `gitlab`.

**Comment by samcro1967** [comment]
@larsl-net  The REGEX returns the first match by default (index 0 if I remember correctly).  You can override it with the index parameter, but it looks like the position of the match you want may change over time???

You could run a script with `cron` and redirect the `curl` to `sort -r` and redirect that to a text file.  Then have Argus run your regex against that file.  It will then be the first result.

**Comment by JosephKav** [comment]
Yeah, what @samcro1967 says is correct. regex will get the match at the specified index (default of 0). So here it's getting the first match on `\"name\":\"v([0-9.]+\-ee)"`, which is `15.1.5-ee`

**Comment by larsl-net** [comment]
Thanks for the answer.
Then I will probably build a solution that provides me the latest version.

What do you think of a new monitor type for the latest_version which executes a command to cover such special cases?

Example for such a type:
```yaml
service:
  gitlab-org/gitlab:
    latest_version:
      type: command
      command: curl -s https://gitlab.com/api/v4/projects/278964/repository/tags | jq -r '.[].name' | sort -Vr | head -n1
      url_commands:
        - type: regex
          regex: \"name\":\"v([0-9.]+\-ee)"
    dashboard:
      icon: https://gitlab.com/gitlab-org/gitlab/-/raw/master/public/slash-command-logo.png
      web_url: https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG.md
```

**Comment by JosephKav** [comment]
I'd prefer to not have a `command` type. You could do this query on the [gitlab changelog](https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG.md) since that appears to have patches with the minor version

```yaml
service:
  gitlab-org/gitlab:
    latest_version:
      type: url
      url: https://gitlab.com/gitlab-org/gitlab/-/raw/master/CHANGELOG.md
      url_commands:
        - type: regex
          regex: '## ([0-9.]+) \([0-9-]+\)'
    dashboard:
      icon: https://gitlab.com/gitlab-org/gitlab/-/raw/master/public/slash-command-logo.png
      web_url: https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG.md
```
> INFO: gitlab-org/gitlab, Latest Release - "15.3.2"
