### ISSUE TITLE
bug: custom_headers not used from root Webhook config

### ISSUE THREAD

**Issue by mytlogos** [release-argus/Argus#173]
**Describe the bug**
The Custom headers defined in the `.webhook.<webhook-id>.custom_headers` Path are not used, but the documentation suggests, that it should be working: [Custom Headers](https://release-argus.io/docs/config/webhook/#custom_headersl).
Defining the `custom_headers` field on the webhook definitinon on the service itself works, but defeats the purpose of having a general config for multiple services, if the same `custom_headers` configuration would need to be repeated on every service.

Neither does it work to define the `custom_headers` field in the defaults configuration for webhooks, though the documentation does not explicitly support this, so that issue would be more of a feature request.

**To Reproduce**
1. Create docker-compose.yml file
2. Create test.yml config file
3. Create dummy python server script file `test_server.py` for reading the webhook request to stdout
4. execute `python3 test_server.py` in same directory as `test_server.py`
5. execute `docker compose up -d` (for compose v2 or `docker-compose up -d` for compose v1)
6. browse to localhost:3333 in browser
7. click on webhooks button to send webhook request on the single available argus service
8. inspect stdout from `test_server.py` script

test_server.py
```python
#!python3
from http.server import BaseHTTPRequestHandler, HTTPServer

hostName = "0.0.0.0"
serverPort = 9000

class MyServer(BaseHTTPRequestHandler):
    def do_POST(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        print(self.headers.as_bytes())
        data = self.rfile.read(int(self.headers["Content-Length"]))
        print(data)

if __name__ == "__main__":        
    webServer = HTTPServer((hostName, serverPort), MyServer)
    print("Server started http://%s:%s" % (hostName, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")

```
docker-compose.yml
```yaml
version: '3.7'

services:
  argus:
    image: releaseargus/argus:latest
    volumes:
      - ./test.yml:/app/config.yml
      - ./storage/:/app/data/
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      ARGUS_UID: 911 # Optional UID override
      ARGUS_GID: 911 # Optional GID override
    ports:
      - 3333:8080
    restart: always

```

test.yml
```yaml
---
webhook:
  deploy:
    type: github
    url: http://192.168.1.13:9000/hooks/deploy
    secret: asdjio
    custom_headers:
      ARGUS-ID: "2"
      ARGUS-VERSION: "as"
service:
  argus:
    comment: 'something about the service maybe?'
    options:
      active: true
      interval: 30m
      semantic_versioning: true
    latest_version:
      type: github
      url: release-argus/Argus
      use_prerelease: false
      url_commands:
        - type: regex
          regex: ^v?([0-9.]+)$
      require:
        regex_content: 'Argus-{{ version }}.linux-amd64'
        regex_version: ^[0-9.]+[0-9]$
        command: ["bash", "check_version.sh", "{{ version }}"]
        docker:
          type: hub
          image: releaseargus/argus
          tag: '{{ version }}'
    webhook:
      deploy:
    dashboard:
      auto_approve: false

```

**Expected behavior**
The output of test_server.py should contain the `ARGUS-ID` and `ARGUS-VERSION` header, as it does when defining it on the service webhook config.

Example output:
```
b'Host: 192.168.1.13:9000\nUser-Agent: Go-http-client/1.1\nContent-Length: 130\nARGUS-ID: portainer\nARGUS-VERSION: 2.16.1\nConnection: close\nContent-Type: application/json\nSOMETHING: foo\nVERSION: 2.16.1\nX-Github-Delivery: f7bhekds-cmxe-8q54-nh30-mvzawglw03gf\nX-Github-Event: push\nX-Github-Hook-Id: 912040744\nX-Github-Hook-Installation-Target-Id: 360840664\nX-Github-Hook-Installation-Target-Type: repository\nX-Hub-Signature: sha1=61b1fa7aa95ca0a9dcface93b3ed370d142ffd01\nX-Hub-Signature-256: \n sha256=0d66bed8c8f12f88924dda26b4a200e045da44ccd39f823da1c73b5e8a6a93e7\nAccept-Encoding: gzip\n\n'
b'{"ref":"refs/heads/master","before":"i64i2fy4szxkz2t3e2mrj7obnidy8n4uhha5ur59","after":"fo7m1x012dku0qowhjhe27io3qu1z6jktby90eqk"}'
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser firefox
 - Version 0.10.3
 - Architecture: amd64

**Smartphone (please complete the following information):**

**Additional context**
