### ISSUE TITLE
Hyperlink to release notes

### ISSUE THREAD

**Issue by thickconfusion** [release-argus/Argus#184]
I want the notification to link me to the release notes. I'm also not able to get any release notes in the notification.

```yaml
notify:
  default_telegram:
    type: telegram
    url_fields:
      token: <secret>
    params:
      chats: "<removed>"
      parsemode: Markdown
      title: Argus
service:
  louislam/uptime-kuma:
    options: {}
    latest_version:
      type: github
      url: louislam/uptime-kuma
    command: []
    notify:
      default_telegram: {}
    webhook: {}
    deployed_version:
      url: <removed>
      basic_auth:
        username: <removed>
        password: <secret>
      regex: app_version{version=\"([0-9.]+)\",major=\"[0-9]+\",minor=\"[0-9]+\",patch=\"[0-9]+\"}
    dashboard:
      icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
      web_url: https://github.com/louislam/uptime-kuma/releases/tag/{{ version }}
```

**Comment by JosephKav** [comment]
You can do this by giving the notify `options` (docs)
e.g.
```yaml
notify:
  default_telegram:
    options:
      message: >-
        <{{ service_url }}|{{ service_id }}> -
        {{ version }} released{% if web_url %}
        (<{{ web_url }}|changelog>){% endif %}
```
This would give

[louislam/uptime-kuma](github.com/louislam/uptime-kuma) - released ([changelog](https://github.com/louislam/uptime-kuma/releases/tag/1.19.0))
