### ISSUE TITLE
bug: Notifications (Matrix) requires username

### ISSUE THREAD

**Issue by tiredofit** [release-argus/Argus#193]
**Describe the bug**
While testing the notification functions, a variety of issues have been identified specifically with the `matrix` type. I have no access to test others at this time.

When referencing the [Shoutrrr instructions](https://containrrr.dev/shoutrrr/v0.6/services/matrix/) it lists that simply a password can be used as an access token. When trying to utilize this with Argus, it fails, requiring the declaration of a Username.
 
**To Reproduce**
Configuration:
````
notify:
  matrix:
    type: matrix
    url_fields:
      #User: monitor
      #Password: thesuerpassword
      Password: accesstoken
      Host: matrix.example.com
      Port: 443

service:
  org/repo:
  ...
  notify:
     matrix: {}
````

**Expected behavior**
Ability to utilize Access Tokens

**Additional context**
Argus details:

````
2023/01/11 20:15:12 DEBUG: 1/1 org/repo Init
service:
  org/repo:
    notify:
      matrix:
        ^ failed to log in: Bad parameter: password
