### ISSUE TITLE
bug: Notifications (Matrix) does not follow "Rooms" declaration

### ISSUE THREAD

**Issue by tiredofit** [release-argus/Argus#194]
**Describe the bug**
While testing the notification functions, a variety of issues have been identified specifically with the `matrix` type. I have no access to test others at this time.

When referencing the [Shoutrrr instructions](https://containrrr.dev/shoutrrr/v0.6/services/matrix/) and Argus instructions it states that one can send messages to a specific "room". If no room is given, it will send to all rooms the user is subscribed to. I am unable to send to a scoped room and it appears to not be registering this configuration.
 
**To Reproduce**
Configuration:
````
notify:
  matrix:
    type: matrix
    url_fields:
      ...
    params:
       DisableTLS: no
       Rooms: #software-updates:example.com
       Title: Argus


service:
  org/repo:
  ...
  notify:
     matrix: {}
````

**Expected behavior**
Ability to send to scoped room

**Additional context**
Argus details:

````
2023/01/11 20:17:20 DEBUG: org/repo (url_commands), Resolved to 3.0
2023/01/11 20:17:20 INFO: org/repo, New Release - "3.0"
2023/01/11 20:17:20 DEBUG: matrix (org/repo), Sending "org/repo - 3.0 released" to "matrix://user:password@matrix.example.com:443/?disableTLS=no" with params=map["disabletls":"no" "rooms":"" "title":"Argus"]
````

FWIW I have also tried by using the Room ID, and Also using `notify.matrix.params.rooms` (lowercase) with no success.
