### ISSUE TITLE
feat: service type dockerhub

### ISSUE THREAD

**Issue by treezio** [release-argus/Argus#207]
## Context
There are some repositories in github that are not managing their versions using the `releases` feature such as https://github.com/confluentinc/kafka-images but still publishing their images on dockerhub.

## Goal
It would be nice to being able to use the dockerhub (it could be extended to other repositories) image tags from a given repository as the released versions.

## Proposal
Some configuration to the following could be set:
```
    latest_version: 
      type: dockerhub
      repository: releaseargus/argus  # repository name
      access_token:  # Dockerhub token for private repositories 
      url_commands:
        - type: regex_submatch  # This searches the image tag
          regex: ^v?([0-9.]+)$
```

I know there is a `latest_version.required.docker` feature but I guess it still needs releases are generated in the github repository.

**Comment by JosephKav** [comment]
Hmm, currently you could query the tags page as `url`. I could add a `github_tags` type that'd query https://api.github.com/repos/confluentinc/kafka-images/tags (we look at `/releases` as this gives you assets uploaded for that release tag). I'll look into that aswell as this `dockerhub` approach soon. Thanks for the feature suggestion :)

```yaml
  confluentinc/kafka-images:
    latest_version:
      type: url
      url: https://github.com/confluentinc/kafka-images/tags
      url_commands:
        - type: regex
          regex: \/releases\/tag\/v?([^"]+)\"
```
