### ISSUE TITLE
bug: github container registry check doesn't allow periods in repo name

### ISSUE THREAD

**Issue by adampetrovic** [release-argus/Argus#247]
**Describe the bug**
Setting up a monitor on the `dgtlmoon/changedetection.io` repository in github, which uses the Github container registry for container packages. I have the following service configuration:
```
changedetection:
    latest_version:
      type: github
      url: dgtlmoon/changedetection.io
      url_commands:
        - type: regex
          regex: ([0-9.]+)$
      require:
        docker:
          type: ghcr
          image: dgtlmoon/changedetection.io
          tag: '{{ version }}'
          token: <redacted>
```

I am running a test command and get the following error.
```
# argus -config.file config.yml -test.service changedetection
service:
  changedetection:
    latest_version:
      require:
        docker:
          image: "dgtlmoon/changedetection.io" <invalid> (non-ASCII)
```

Removing `.io` from the image name allows the validation to pass.

**To Reproduce**
1. Place the above in a config
2. Run `argus -config.file config.yml -test.service changedetection`

**Expected behavior**
Validation passes

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
