### ISSUE TITLE
bug: setting a default notifier to an empty map has no effect

### ISSUE THREAD

**Issue by ThinkChaos** [release-argus/Argus#272]
**Describe the bug**
I want to use the same notifier for all services, which I expected to work by setting it up via `defaults` like so:
```yaml
defaults:
  service:
    notify:
      EXAMPLE_NOTIFY_ID: {}
notify:
  EXAMPLE_NOTIFY_ID:
    type: shoutrrr
service:
  argus:
    latest_version:
      type: github
      url: release-argus/Argus
```

Unfortunately that is not supported while the Argus docs make it sound like it should work.  
In addition, with that config, `-test.notify` crashes.

**To Reproduce**
```
$ argus -config.file=$aboveConfig -test.notify EXAMPLE_NOTIFY_ID
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90aba1]

goroutine 1 [running]:
github.com/release-argus/Argus/testing.findShoutrrr({0x7ffc41489794, 0xf}, 0xc0000a3180, 0xc0000efd08?, 0xc0000efd10)
        github.com/release-argus/Argus/testing/shoutrrr.go:113 +0x761
github.com/release-argus/Argus/testing.NotifyTest(0xc0000aa110, 0xc0000ba550?, 0x1955960)
        github.com/release-argus/Argus/testing/shoutrrr.go:43 +0xb5
main.main()
        github.com/release-argus/Argus/cmd/argus/main.go:59 +0x21d
```

(Note that the config snippet above will probably not fully work since the notify is missing some required fields, but at least Argus shouldn't crash/fail at this point, and should try to use the notifier).

**Expected behavior**
Argus should detect `defaults.service.notify.*` is set and copy it to the service's config.

Looking at the code, it looks like the `service.Defaults` struct doesn't have a `Notify` field ([src](https://github.com/release-argus/Argus/blob/0.12.1/service/types.go#L37)). So I'd also expect Argus to complain about unknown options in the YAML file instead of silently ignoring them.  
In Go this is achievable using `Decoder.KnownFields` ([docs](https://pkg.go.dev/gopkg.in/yaml.v3#Decoder.KnownFields)).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Argus 0.12.1

**Comment by ThinkChaos** [comment]
Confirmed this works on my side!

**Comment by samcro1967** [comment]
@JosephKav I was not able to get this to work, but might be because I have them mixed for testing.  I had three notifications setup for each service.  I moved one of them to the defaults section, and left 2 defined for each service.  When I tested a service, only 1 of the 3 worked.  Here is the abbreviated config.

```
defaults:
  service:
    options:
      interval: 30m
    notify:
      GOTIFY_NOTIFICATION: {}
notify:
  DISCORD_NOTIFICATION:
    type: discord
    options:
      delay: 0s
      max_tries: "3"
      message: '{{ service_id }} - {{ version }} released.'
    url_fields:
      token:  <redacted>
      webhookid: " <redacted>"
  GOTIFY_NOTIFICATION:
    type: gotify
    options:
      delay: 0s
      max_tries: "3"
      message: '[{{ service_id }}]({{ service_url }}) - {{ version }} released{% if web_url %} ([changelog]({{ web_url }})){% endif %}'
    url_fields:
      host: osu.gotify
      port: "8132"
      token:  <redacted>
    params:
      disabletls: "yes"
      title: Argus Notification
  PUSHOVER_NOTIFICATION:
    type: pushover
    options:
      delay: 0s
      max_tries: "3"
      message: '[{{ service_id }}]({{ service_url }}) - {{ version }} released{% if web_url %} ([changelog]({{ web_url }})){% endif %}'
    url_fields:
      token: <redacted>
      user:  <redacted>
  Dozzle:
    notify:
      DISCORD_NOTIFICATION: {}
      PUSHOVER_NOTIFICATION: {}
    ...
```

When Dozzle updated, I received a `Discord` notification, but none in `Pushover` or `Gotify`.  I did a manual cli test of all 3 notifications and they all still worked as expected.  There are no errors in the container log.  Log level is currently set to info.

I would have thought in a mixed mode either the global option (`Gotify`) would work or the ones specified in the service (`Discord` and `Pushover`) would work if having them in both places did not work.

I then moved all notifications to the defaults section and removed all notifications from each service, and did not get any notification when plex updated.  Guessing I am missing something or just don't have the config quite right?

**Comment by JosephKav** [comment]
@samcro1967, the way the `defaults.service.notify` works is that if `service.X.notify` is empty, it will become those in defaults. But no values under each notify in `defaults.service.notify` are ever used, it'll just be treated like an empty map.

e.g.
```yaml
defaults:
  service:
    notify:
      example:
        options:
          message: foo
notify:
  example:
    type: discord
    options:
      delay: 0s
      max_tries: "3"
      message: '{{ service_id }} - {{ version }} released.'
    url_fields:
      token:  <redacted>
      webhookid: "<redacted>"
service:
  test:
    latest_version:
      type: github
      url: release-argus/Argus
```

'test' should be treated as
```yaml
  test:
    latest_version:
      type: github
      url: release-argus/Argus
    notify:
      example: {}
```
so the `defaults.service.notify.example.X` is ignored
