### ISSUE TITLE
feat: Display index thru GUI

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#273]
When index is set through the config file, it is not displayed in the GUI.  Is it possibel to add this to be displayed/updated through the GUI?

```
  Cadvisor:
    options:
      semantic_versioning: false
    latest_version:
      type: url
      url: https://github.com/google/cadvisor/tags
      url_commands:
        - type: regex
          regex: releases\/tag\/v([0-9.]+)
          index: 8
```

![image](https://github.com/release-argus/Argus/assets/2319445/fc40522a-f4de-4dfc-8cc7-dda413989a44)
