### ISSUE TITLE
feat: Support for running bash commands as a new release action

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#32]
**Describe the solution you'd like**
```yaml
service:
  release-argus/argus:
    commands:
      - 'bash /opt/deploy.sh'
      - 'bash /opt/other.sh'
```
