### ISSUE TITLE
feat: Support for Telegram

### ISSUE THREAD

**Issue by djmattyg007** [release-argus/Argus#33]
**Is your feature request related to a problem? Please describe.**
I don't use Slack or Gotify.

**Describe the solution you'd like**
I'd like to be able to specify an arbitrary set of Telegram bot API credentials, as well as an arbitrary chat ID. Messages should arrive at that chat. 

**Describe alternatives you've considered**
I tried looking for a Tekegram plugin for Gotify, but was unsuccessful.

**Comment by djmattyg007** [comment]
Perhaps consider using a library like https://github.com/nikoksr/notify ?

**Comment by samcro1967** [comment]
Might want to look at [apprise](https://github.com/caronc/apprise).  Pretty large library of supported options.

**Comment by JosephKav** [comment]
apprise is a Python module, so can't use that sadly.
I don't really see the use of that notify library. You still have to implement the services yourself, you just then give them to that notify and send with that. So you'd still need to add support for every service yourself.
I'll work on adding Telegram support later on 👍

**Comment by samcro1967** [comment]
[Shoutrrr](https://github.com/containrrr/shoutrrr) is another alternative written in go.  It does not have as many services, but might also be worth a look.

**Comment by djmattyg007** [comment]
Using a library like notify lets you avoid all the implementation details and use a simple interface in your own code. The alternative is learning the minutiae of every single service's request formats and the like.

**Comment by JosephKav** [comment]
> [Shoutrrr](https://github.com/containrrr/shoutrrr) is another alternative written in go. It does not have as many services, but might also be worth a look.

This looks more preferable to notify (imo). Thinking I'll replace `slack:` and `gotify:` with `notify:` (that uses Shoutrrr not Notify). Then make that read yaml like this
```yaml
service:
  release-argus/argus:
    ....
    notify:
      argus_notifications:
        type: slack
        token: xyz
        channel: something
        params:
          bot_name: argua
          color: #ff8000
          icon: github
          title: New release
```

**Comment by djmattyg007** [comment]
It would be nice if we could specify multiple different notification targets, but that’s just a nice to have.

**Comment by JosephKav** [comment]
> It would be nice if we could specify multiple different notification targets, but that’s just a nice to have.

What do you mean by 'different notification targets'? You can (and will still) be able to setup multiple of each type of notification to go to different places.
I have Shoutrrr mostly working, am just working on automated conversions to the new format for existing slacks (to slack/mattermost) and gotify. Am also trying to figure out how the Shoutrrr code works so that I can PR icon support for Mattermost

**Comment by samcro1967** [comment]
@djmattyg007 Look into mailrise.  It is an SMTP gateway that uses apprise under the covers.  Use Shoutrr to send email to mailrise and use mailrise to then forward.  It allows you to setup different email addresses.  Each can have one or more destinations.  I use this for all of my apps.  Each app has its own channel in Discord and Gotifty.  Some I send emails.  You then have one config for all of your apps.  If you change email addresses, you have one place to go to change all of your apps.  Or if you want to change from Slack to Discord, one place to go.  No longer have to remember every place you have to go make changes.  Also opens up a lot more options of places to send.

**Comment by JosephKav** [comment]
After too many commits, I'd say that this is about ready in https://github.com/release-argus/Argus/pull/63. Have implemented conversions of `slack`/`gotify` to not make this a breaking change, but I bet there will still be a config that breaks! :/. Gonna try some more testing of random configs tomorrow and ensure they all work.
> Currently, switching to Shoutrrr is gonna lose us Gotify extras (unless me/someone else adds them to Shoutrrr), and until the next Shoutrrr release, we'll lose support for sending icons with our Mattermost webhooks

**Comment by JosephKav** [comment]
Right I've done a bunch more testing and finally merged the PR. Tried to get conversions to handle places where you may have had a `gotify` and a `slack` named the same, but in the end I gave up as I thought a few edge cases would fail that way and I just want to get this out. It'll detect where `slack` is for `slack` by 'hooks.slack.com' being in the `url` and assume it's for `mattermost` otherwise. Then it will suffix all existing `slack`/`gotify` names with the type it detects, so they'll either end in '_gotify', '_mattermost' or '_slack', but I believe they should all continue working.

I'd appreciate some of you testing this and reporting back to me (with the log) if ur config fails with this new image.
The Docker `:master` image should be out in the next 10 mins or so

**Comment by samcro1967** [comment]
@JosephKav So Gotify notification would now look something like this using the shourtrr format for url's?

```
notify:
  GOTIFY_NOTIFICATION:
    url: gotify://ip_address:port
    token: <gotify_token>
    title: Argus Notification
    message: '{{ service_id }} - {{ version }} released.'
    extras:
      client_display: text/plain
      client_notification: '{{ web_url }}'
    priority: 5
    delay: 0s
    max_tries: 3
```

And each service would look like:
```
    notify:
      GOTIFY_NOTIFICATION: {}
```

**Comment by JosephKav** [comment]
> @JosephKav So Gotify notification would now look something like this using the shourtrr format for url's?

```yaml
notify:
  GOTIFY_NOTIFICATION:
    type: gotify
    options:
      message: '{{ service_id }} - {{ version }} released.'
      delay: 0s
      max_tries: 3
    url_fields:
      host: ip_address
      port: 443
      token: <gotify_token>
    params:
      title: Argus Notification
      priority: 5
```

Forgot to link the updated docs, sorry! https://deploy-preview-13--release-argus.netlify.app/docs/config/notify/#gotify
(I'll merge them to release-argus.io once I do a release)
We've lost the `extras` ability with Gotify under Shoutrrr sadly

**Comment by samcro1967** [comment]
I updated config.yml and built and deployed a new local image.  No errors in the logs.  Will let you know what happens once an app is updated.

**Comment by JosephKav** [comment]
> I updated config.yml and built and deployed a new local image. No errors in the logs. Will let you know what happens once an app is updated.

Ideally, you should have been able to use the existing config. Did you try that? You can test the notifiers with `-test.notify NAME`

**Comment by samcro1967** [comment]
I did not, but easy enough for me to roll back the config.yml.  Argus starts fine with no errors.  I see if added _gotify to my notification name.  When I test it, I do get an error.  It is trying to send an https request to an http server.

**Comment by JosephKav** [comment]
What `url` were you using?

**Comment by JosephKav** [comment]
I'm guessing (and hoping) one without `http` or `https` as I've made it default the port to `443` if it can't find those or a host:<PORT>

**Comment by samcro1967** [comment]
just `osu.gotify:8132`.

**Comment by JosephKav** [comment]
Ah, so you'll need `params.disabletls` under this notify

**Comment by JosephKav** [comment]
@samcro1967 What are you using as host in that one? Odd that it's got two ports

**Comment by samcro1967** [comment]
`192.168.1.104:8132`  Looks like you are automatically wrapping https: and 443 around whatever is entered into the Host field.  Maybe the `DisableTLS: yes` is not working.  I would think that should at least change https to http.  You may want to add another url_field for port.  You will have no way of knowing what port people are running services on.  Would be cleaner I think to let folks know they have to specify both.  Then you will know the port for sure and are not assuming it is on either 80 or 443
???

**Comment by JosephKav** [comment]
> `192.168.1.104:8132` Looks like you are automatically wrapping https: and 443 around whatever is entered into the Host field. Maybe the `DisableTLS: yes` is not working. I would think that should at least change https to http. You may want to add another url_field for port. You will have no way of knowing what port people are running services on. Would be cleaner I think to let folks know they have to specify both. Then you will know the port for sure and are not assuming it is on either 80 or 443 ???

There is one for port, it just defaults to `443`. Looks like its not getting the params correctly, may be only in the testing call. Trying to fix currently

**Comment by samcro1967** [comment]
Totally missed the port in the docs.  I updated and it is now trying to get to `"https://osu.gotify:8132`.

**Comment by JosephKav** [comment]
> Totally missed the port in the docs. I updated and it is now trying to get to `"https://osu.gotify:8132`.

Yeah, I've pushed a fix for that. The `master` tag should be updated in <10 mins. The params from defaults/notify weren't being passed down to the service notify

**Comment by JosephKav** [comment]
FYI, you can track the build of `:master` (happens every commit to the `master` branch) [here](https://github.com/release-argus/Argus/actions/workflows/build-docker.yml)

**Comment by JosephKav** [comment]
> Test notification worked with the latest version and the new syntax. Do you want me to roll the config back to the old syntax and test that as well?

That'd be nice, but only if you woulnd't mind and it's not too much hassle 😄

**Comment by samcro1967** [comment]
The old config gave me the https to an http message.

```
docker exec -it argus bash -c "cd /etc/argus && argus -test.notify GOTIFY_NOTIFICATION_gotify"
INFO: Testing (GOTIFY_NOTIFICATION_gotify),
ERROR: GOTIFY_NOTIFICATION_gotify, failed to send notification to Gotify: Post "https://osu.gotify:8132/message?token=AdMn4Ycrgo8SUKu": http: server gave HTTP response to HTTPS client
ERROR: GOTIFY_NOTIFICATION_gotify, failed to send notification to Gotify: Post "https://osu.gotify:8132/message?token=AdMn4Ycrgo8SUKu": http: server gave HTTP response to HTTPS client
ERROR: GOTIFY_NOTIFICATION_gotify, failed to send notification to Gotify: Post "https://osu.gotify:8132/message?token=AdMn4Ycrgo8SUKu": http: server gave HTTP response to HTTPS client
ERROR: GOTIFY_NOTIFICATION_gotify, failed 3 times to send a gotify message to gotify://osu.gotify:8132/AdMn4Ycrgo8SUKu
ERROR: Testing (GOTIFY_NOTIFICATION_gotify), Message failed to send with "GOTIFY_NOTIFICATION_gotify" config
failed to send notification to Gotify: Post "https://osu.gotify:8132/message?token=AdMn4Ycrgo8SUKu": http: server gave HTTP response to HTTPS client x 3
```

Here is the old config:
```
gotify:
  GOTIFY_NOTIFICATION:
    url: http://osu.gotify:8132
    token: <redacted>
    title: Argus Notification
    message: '{{ service_id }} - {{ version }} released.'
    extras:
      client_display: text/plain
      client_notification: '{{ web_url }}'
    priority: 5
    delay: 0s
    max_tries: 3
```

**Comment by JosephKav** [comment]
@samcro1967 
```
		url = strings.TrimPrefix(url, "http://")
		if strings.HasPrefix(url, "http://") {
			converted.SetParam("disabletls", "yes")
		}
```
🤦 
I strip the `http://` before I check for it and disabletls!

**Comment by samcro1967** [comment]
Something else I should try?

**Comment by JosephKav** [comment]
> Something else I should try?

Not that I can think of? I'm saying it's all working as far as I can see w.r.t Gotify and HTTP. My command log was just to show that it did pick it up as http and disabletls, so tried http://. It's meant to fail as I pointed it at a non-existant server as I disabled http on my one after the testing earlier worked

**Comment by samcro1967** [comment]
So with the old config I specified `http://osu.gotify:8132` as the URL.  The notification was sent to `https://osu.gotify:8132`.  It doesn't look like the strip is working to me with the old config, but maybe I am misunderstanding what you are saying.

**Comment by JosephKav** [comment]
> So with the old config I specified `http://osu.gotify:8132` as the URL. The notification was sent to `https://osu.gotify:8132`. It doesn't look like the strip is working to me with the old config, but maybe I am misunderstanding what you are saying.

Did you make sure to repull `:master`? I just tried on docker with your config and it worked. Changed my Gotify back to HTTP to confirm
```
❯ sudo docker exec -it c9265400f10d bash -c "cd /etc/argus && argus -test.notify GOTIFY_NOTIFICATION_gotify"
INFO: Testing (GOTIFY_NOTIFICATION_gotify), 
DEBUG: GOTIFY_NOTIFICATION_gotify, Sending "TEST - NAME_OF_SERVICE - MAJOR.MINOR.PATCH released." to "gotify://gotify.example.io:444/<SECRET>" with params=map["disabletls":"yes" "priority":"5" "title":"Argus Notification"]
INFO: Testing (GOTIFY_NOTIFICATION_gotify), Message sent successfully with "GOTIFY_NOTIFICATION_gotify" config
```

**Comment by samcro1967** [comment]
Just rebuilt the container and retestd.  It worked.  I wonder if I pulled it too soon after you made the last commit.  Not sure if Github uses a CDN and maybe I had not replicated yet from where I pulled it.  I will test discord tomorrow.  :-)

**Comment by samcro1967** [comment]
Tested Discord and works as expected.  Also tried email, but am getting an error which I am guessing it in my config, but I am not seeing it.  I see MAILRISE_NOTIFICATION when I do a -config.check.

**config.xml global block**
```
notify:
  MAILRISE_NOTIFICATION:
    type: smtp
    url_fields:
      Host: osu.mailrise
      Port: 8025
    params:
      FromName: Argus
      FromAddress: argus@mydomain.net
      ToAddress: argus@mydomain.net
      Auth: None
      Subject: '{{ service_id }} Release'
      UseHTML: yes
      UseStartTLS: no
```

**logs**
```
docker exec -it argus bash -c 'cd /etc/argus && argus -test.notify MAILRISE_NOTIFICATION'
INFO: Testing (MAILRISE_NOTIFICATION),
ERROR: Testing (MAILRISE_NOTIFICATION), notify:
  MAILRISE_NOTIFICATION:
    ^ unknown service ""
```
