### ISSUE TITLE
Positive Look Behind Question

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#34]
I am getting an error using a positive look behind.  It works at https://regex101.com/.  I tried various escapes for the `?` and `<`.  Any ideas?

**Logs**
```
panic: regexp: Compile(`(?<=\"version\":\s\")([0-9.]+)\"`): error parsing regexp: invalid or unsupported Perl syntax: `(?<`
```

**Regex**
```
(?<=\"version\":\s\")([0-9.]+)\"
```

**Comment by JosephKav** [comment]
Go doesn't seem to support lookarounds
Source: https://stackoverflow.com/questions/38933898/error-parsing-regexp-invalid-or-unsupported-perl-syntax

**Comment by samcro1967** [comment]
I think I got it to work correctly with the config below.  However it is not showing up in the GUI as up to date, but as no successful query even though the data is in config.xml and matches.  Tried it in incognito mode to rule out browser cache.  Stopped and restarted the container.  Removed and readded the container also.  Very odd to me.

![image](https://user-images.githubusercontent.com/2319445/168482192-8743c122-dcc5-42dd-8821-0162a293a030.png)

**config.xml**
```
  Sonarr/Sonarr:
    type: url
    url: http://services.sonarr.tv/v1/releases
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: \"version\":\s\"([0-9.]+)\"
        index: 1
    web_url: http://'ocal.sonarr:8079/sonarr/system/updates
    icon: https://raw.githubusercontent.com/NX211/homer-icons/master/png/sonarr.png
    deployed_version:
      url: http://local.sonarr:8079/sonarr/api/v3/system/status?apikey=<redacted>
      json: version
    status:
      current_version: 3.0.8.1519
      current_version_timestamp: "2022-05-15T12:55:53Z"
      latest_version: 3.0.8.1519
      latest_version_timestamp: "2022-05-15T12:55:53Z"
```

**Comment by JosephKav** [comment]
So that regex fails with what's returned by the HTTP query. Turning the log level up to DEBUG, you can see that no spaces are returned in the JSON, so the `\s` part fails the regex, and omitting that, or making it optional with a `?` work - `\"version\":\s?\"([0-9.]+)\"` or `\"version\":\"([0-9.]+)\"`

**Comment by samcro1967** [comment]
Yes, that fixes the query issue, but back to figuring out another ay to strip off version with go's perl regex implementation.

![image](https://user-images.githubusercontent.com/2319445/168487186-b8532aa5-1f06-4969-8492-6ff88b812d65.png)

**Comment by JosephKav** [comment]
Ah, that you can fix by making the type `regex_submatch`. A use-case for `regex` would be when you want the 2nd regex match as `regex_submatch` will only match on the first

**Comment by samcro1967** [comment]
Using regex_submatch gives me 3.0.8.1507 from v3-stable which is the first occurrence of the word version.  I needed to use regex with index of 1 to get to the second match for v3-nightly.

http://services.sonarr.tv/v1/releases

I think the quickest path will be to write a bash script to curl the page, pull out what is needed, dump it to a text file, host it on a local web server, and get the latest version from there in Argus.  Just have cron update it once an hour.

**Comment by JosephKav** [comment]
Ah, the exact use-case for this regex command! The quickest solution would be to use your original regex url_command, then add another one that does a submatch on that regex

```yaml
    url_commands:
      - type: regex
        regex: \"version\":\s?\"([0-9.]+)\"
        index: 1
      - type: regex_submatch
        regex: \"version\":\s?\"([0-9.]+)\"
```

gives me the nightly version
```bash
❯ ./argus -config.file test.yml -test.service Sonarr/Sonarr
INFO: Testing (Sonarr/Sonarr), 
INFO: Sonarr/Sonarr, Latest Release - "3.0.8.1519"
```

**Comment by JosephKav** [comment]
[This](https://github.com/release-argus/Argus/pull/35) PR fixes that index issue btw

**Comment by samcro1967** [comment]
Yes, that did work.  Didn't realize they could be stacked.  That is a game changer.  I have 5 apps working now.  Looks like you added the discussion board.  I could add them to the show and tell section if that would be of value.

**Comment by JosephKav** [comment]
> Yes, that did work. Didn't realize they could be stacked. That is a game changer. I have 5 apps working now. Looks like you added the discussion board. I could add them to the show and tell section if that would be of value.

Perfect!
Yeah, that'd definitely be interesting for me if you did please. Always nice to see people like you taking in an interest in what I've been working on

**Comment by samcro1967** [comment]
Just added what I have so far.

**Comment by samcro1967** [comment]
@JosephKav I noticed today Sonarr stopped working.  When I have semantic versioning set to false I get:
```
No version matching the conditions specified could be found for "Sonarr/Sonarr" at "http://services.sonarr.tv/v1/releases"
```

If I comment it out, I then get:
```
ERROR: Testing (Sonarr/Sonarr), failed converting "3.0.8.1520" to a semantic version. If all versions are in this style, consider adding json/regex to get the version into the style of 'MAJOR.MINOR.PATCH' (https://semver.org/), or disabling semantic versioning (globally with defaults.service.semantic_versioning or just for this service with the semantic_versioning var)
ERROR: Testing (Sonarr/Sonarr), failed converting "3.0.8.1520" to a semantic version. If all versions are in this style, consider adding json/regex to get the version into the style of 'MAJOR.MINOR.PATCH' (https://semver.org/), or disabling semantic versioning (globally with defaults.service.semantic_versioning or just for this service with the semantic_versioning var)
```

So it seems like the regex is working as it is finding the right version of 3.0.8.1520.  This worked yesterday.  Possibly one of the updates is impacting this?

Current config.xml
```
  Sonarr/Sonarr:
    type: url
    url: http://services.sonarr.tv/v1/releases
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: \"version\":\s\"([0-9.]+)\"
        index: 1
      - type: regex
        regex: '[0-9.]+'
    web_url: http://local.sonarr:8079/sonarr/system/updates
    icon: https://raw.githubusercontent.com/NX211/homer-icons/master/png/sonarr.png
    deployed_version:
      url: http://local.sonarr:8079/sonarr/api/v3/system/status?apikey=<redacted>
      json: version
```
