### ISSUE TITLE
feat: Ability to replace characters in either the latest_version or deployed_version

### ISSUE THREAD

**Issue by theS1LV3R** [release-argus/Argus#345]
**Is your feature request related to a problem? Please describe.**
Minio exposes its versions in the format of `2024-01-01T16:36:33Z` on the server, through metrics. However, the tags on GitHub are in the format of `2024-01-01T16-36-33Z`. Same version, different strings.

**Describe the solution you'd like**
Either adding another command to `latest_version.url_commands`, something like `type: template` that would let you template and change the version however you want, or adding `url_commands` to `deployed_version` with the same concept.

**Describe alternatives you've considered**
Some regex wonkery could be done, but that is a pain in the ass to develop, and having this feature would make it easier for future users with the same issue as well.

**Additional context**

**Comment by JosephKav** [comment]
Ah that's an odd one. I'm not really wanting to duplicate url_commands to deployed_version, so am leaning towards your template option.
How about I add it inside the `regex` url_command? So something like 
```yaml
    - type: regex
      regex: ([\d-]+)T(\d+)-(\d+)-(\d+)Z
      template: $1T$2:$3:$4Z
```
This'd match on the `2024-01-01T16-36-33Z` tag and return the same as the deployed version, `2024-01-01T16:36:33Z`.
I'd add a checkbox or something to the webui for toggling this `template` field for `regex` type url_commands

**Comment by theS1LV3R** [comment]
Hm, I just discovered something interesting: The full tag on the GitHub repo is `RELEASE.2024-01-05T22-17-24Z`, while what MinIO itself reports is `2024-01-05T22:17:24Z`, like we already know. However the Docker container is tagged as `RELEASE.2024-01-05T22-17-24Z`, so I can't copy paste from the Web-UI any more since the release is now technically `2024-01-05T22:17:24Z`.

With changing the GitHub tag I also now have to do this for the web_url:
```yaml
    dashboard:
      web_url: https://github.com/minio/minio/releases/tag/RELEASE.{{ version | split:":" | join:"-" }}
```

Would having an option to template the version reported by the URL be more correct? I wasn't anticipating this would happen :sweat_smile:

**Comment by JosephKav** [comment]
Ah, didn't think of it affecting the web_url. By "template the version reported by the URL", do you mean template the deployed version?

**Comment by theS1LV3R** [comment]
Yes exactly, I see I wasn't that clear on it. In this case it would be changing `2024-01-05T22:17:24Z` into `RELEASE.2024-01-05T22-17-24Z` instead of `RELEASE.2024-01-05T22-17-24Z` into `2024-01-05T22:17:24Z`.

Just for reference (to make sure everyone is on the same page):
- GitHub tag (`latest_version`): `RELEASE.2024-01-05T22-17-24Z`
- Docker image tag: `RELEASE.2024-01-05T22-17-24Z`
- Reported by MinIO (`deployed_version`): `2024-01-05T22:17:24Z`

**Comment by theS1LV3R** [comment]
Just got around to testing it now: Works perfectly! :heart:

For anyone else who stumbled into the same problem as me, and just want to use the new feature without thinking too much, this config is what I ended up using in the end for MinIO:

```yaml
services:
  minio/minio:
    options:
      semantic_versioning: false
    latest_version:
      type: github
      url: minio/minio
    deployed_version:
      url: https://minio-api.example.com/minio/v2/metrics/cluster
      # 2024-01-18T22:51:28Z
      regex: minio_software_version_info{.*version="([0-9\-]+)T(\d+):(\d+):(\d+)Z".*}
      regex_template: "RELEASE.$1T$2-$3-$4Z"
    dashboard:
      web_url: https://github.com/minio/minio/releases/tag/{{ version }}
      icon: https://avatars.githubusercontent.com/u/695951
```
