### ISSUE TITLE
feat(web): custom favicon support

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#354]
Adding favicon overrides
```yaml
settings:
  web:
    favicon:
      svg: URL  # favicon.svg
      png: URL  # apple-touch-icon.png
```
