### ISSUE TITLE
error --> create "" failed (fetches failed) latest_version - failed converting

### ISSUE THREAD

**Issue by prince20112003** [release-argus/Argus#361]
I am getting this error when i try to add a software named greenbone to argus.
the link to the webpage is : https://www.greenbone.net/en/documents/
RegEx: \d+.\d+

[error-greenbone.txt](https://github.com/release-argus/Argus/files/14244675/error-greenbone.txt)

**Comment by JosephKav** [comment]
it says that it `failed converting "X" to a semantic version. If all versions are in this style, consider adding url_commands to get the version into the style of 'MAJOR.MINOR.PATCH' (https://semver.org/), or disabling semantic versioning (globally with defaults.service.semantic_versioning or just for this service with the semantic_versioning var)`

It doesn't look like you have that regex in a url_command as I get a variation of that message on a query with only that URL

**Comment by prince20112003** [comment]
thanks for the quick response. but can you explain a bit in depth?

**Comment by JosephKav** [comment]
You've got it querying that URL to get a version number. You can add url_commands to extract specific text from that page, e.g. RegEx.
I don't know what version you want, but if you wanted the GMP version, you could add a url_command with RegEx `GMP.*Version ([\d.]+)`

```yaml
  Greenbone:
    latest_version:
      type: url
      url: https://www.greenbone.net/en/documents/
      url_commands:
        - type: regex
          regex: GMP.*Version ([\d.]+)
```
