### ISSUE TITLE
feat: Ability to specify environment variables in config

### ISSUE THREAD

**Issue by theS1LV3R** [release-argus/Argus#362]
**Is your feature request related to a problem? Please describe.**
At the moment, Argus supports setting certain configuration elements through environment variables, e.g. `ARGUS_SERVICE_LATEST_VERSION_ACCESS_TOKEN` will set the `service.*.latest_version.access_token` config elements.

However this doesn't work very well for each service, for example I can't do `ARGUS_SERVICE_LOUISLAM_UPTIME_KUMA_DEPLOYED_VERSION_BASIC_AUTH_PASSWORD` to specify the value for `service.louislam/uptime-kuma.deployed_version.basic_auth.password`. (May be a bug, but I couldn't get it to work at least.)

**Describe the solution you'd like**
Instead of a mapping from environment variables to config properties, allow config properties to fetch from the environment. Then it would be possible to do something like this:

```yaml
service:
  louislam/uptime-kuma:
    deployed_version:
      basic_auth:
        password: $UPTIME_KUMA_PASSWORD
```

This could also be used with fallbacks the way bash does it, something like this:
```yaml
service:
  louislam/uptime-kuma:
    deployed_version:
      basic_auth:
        password: ${UPTIME_KUMA_PASSWORD:-some_default_password}
```

**Describe alternatives you've considered**
Not sure if there are any, seeing as hardcoding passwords in a git-committed file isn't a good idea exactly.

**Additional context**
None.
