### ISSUE TITLE
ERROR: release-argus/argus, Get "http://192.168.1.104:8111/api/v1/version": EOF

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#44]
I noticed yesterday that the current version for Argus started failing.  I can curl `http://192.168.1.104:8111/api/v1/version` from the container and get the expected results so it does not appear to be a connectivity issue.

I see the following in the logs:
`ERROR: release-argus/argus, Get "http://192.168.1.104:8111/api/v1/version": EOF`

I checked the docs after the project rename thinking something might have been updated, but not seeing anything other than the project name in the Github URL.

**Config.xml for Argus**
```
  release-argus/argus:
    type: github
    url: release-argus/argus
    web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
    icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
    deployed_version:
      url: http://192.168.1.104:8111/api/v1/version
      json: version
```

I have also noticed that once it does that check a blank line is added in config.xml after the Argus section.  On container restart, this causes it to be the only service parsed.  Removing the container, removing the blank line from config.xml, and restarted the container then parses all services again.
