### ISSUE TITLE
feat: Support for service name variable

### ISSUE THREAD

**Issue by MauritsMonteyne** [release-argus/Argus#442]
**Is your feature request related to a problem? Please describe.**
No, this more of config syntax improvement

**Describe the solution you'd like**
The addition of an optional service variable called `name` that will be shown on the cards instead of the service ID. If not defined it should use the ID instead, this way it won't breaking existing setups.

```yaml
service:
  uptimekuma:
    name: "Uptime Kuma"
    latest_version:
      type: github
      [...]
```

**Describe alternatives you've considered**
Because yaml is pretty flexible some of these examples could be used as well, but in my opinion it doesn't look that great and feels a bit off.
```yaml
service:
  "Uptime Kuma":
    latest_version:
      type: github
      [...]
```
or
```yaml
service:
  Uptime Kuma:
    latest_version:
      type: github
      [...]
```
