### ISSUE TITLE
Config File Suggestions

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#50]
If you are open to a suggestion, I would probably make a few tweaks to the config.yml structure to make it a little easier to navigate for new users.  I realize this would be a breaking change.  Maybe it could be incorporated into the version that adds settings thru the GUI.  First step is to validate the config.xml structure and adjust accordingly.  Below would be my suggestion.

**Current Example**
```
  Sonarr/Sonarr:
    type: url
    url: http://services.sonarr.tv/v1/releases
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: \"version\":\s?\"([0-9.]+)\"
        index: 1
    web_url: http://osu.sonarr:8079/sonarr/system/updates
    icon: https://raw.githubusercontent.com/NX211/homer-icons/master/png/sonarr.png
    deployed_version:
      url: http://osu.sonarr:8079/sonarr/api/v3/system/status?apikey=428f9a8d1420426ca21a891c928594b5
      json: version
```
Proposed Example
```
  Sonarr/Sonarr:
    options:
      semantic_versioning: false
    latest_version:
      type: url
      url: http://services.sonarr.tv/v1/releases
      url_commands:
        - type: regex
          regex: \"version\":\s?\"([0-9.]+)\"
          index: 1
    dashboard:
      web_url: http://local.sonarr:8079/sonarr/system/updates
      icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/png/sabnzbd.png
    deployed_version:
      url: http://local.sonarr:8079/sonarr/api/v3/system/status?apikey=<redacted>
      json: version
```

**Comment by JosephKav** [comment]
Hey @samcro1967, could I get your thoughts on the layout for the new notification system please?
currently:
(max config)
```yaml
service:
  release-argus/argus:
    ....
    notify:
      slack_example:
        type: slack
        max_tries: 1
        message: '{{ web_url }} something'
        delay: 1h
        token: xyz
        channel: something
        params:
          botname: argus
          color: #ff8000
          icon: github
          title: New release
```
(min config)
```yaml
service:
  release-argus/argus:
    ....
    notify:
      slack_example:
        type: slack
        token: xyz
        channel: something
```

In the style of your suggestion (that I'll probably do, or quite similar to)
(max config)
```yaml
service:
  release-argus/argus:
    ....
    notify:
      slack_example:
        type: slack
        options:
          max_tries: 1
          message: '{{ web_url }} something'
          delay: 1h
        url_fields:
          token: xyz
          channel: something
        params:
          botname: argus
          color: #ff8000
          icon: github
          title: New release
```
(min config)
```yaml
service:
  release-argus/argus:
    ....
    notify:
      slack_example:
        type: slack
        url_fields:
          token: xyz
          channel: something
```

I *could* probably do something like
```yaml
service:
  release-argus/argus:
    ....
    notify:
      slack_example:
        slack:
          token: xyz
          channel: something
```
but I think that way looks too list-ey and people will probably have the type of notification as part of the id for that notification (`slack_example` here)

My personal favourite, atm, is the one with `type`, `options`, `url_fields` and `params`. Am open to renaming the those, they're just based off https://containrrr.dev/shoutrrr/v0.5/services/slack/ (style is the same for all services, just what options go in them changes a bit)

**Comment by samcro1967** [comment]
I like your suggestion.  Are you planning to support multiple notifications per service?  If not, you could simplify to something like this unless you really wanted a name for the notification service.
```
service:
  release-argus/argus:
    ....
    notify:
      type: slack
          token: xyz
          channel: something
```
You could reference the name simply by `release-argus/argus.notify` from a code perspective.  I would probably add type in front of the notification type just for consistency with the other service blocks.

If you wanted to add a name, I would maybe do it this way:
```
service:
  release-argus/argus:
    ....
    notify:
      name: MySlackServer
          type: slack
          token: xyz
          channel: something
```

Probably just me nitpicking, but I would call it `max_retries` instead of `max_tries` just to align with what I at least to perceive industry standard langauge.  :-)

**Comment by JosephKav** [comment]
`max_retries` would make a lot more sense from a user perspective. I just went for `max_tries` as then I could just take that var and subtract until it's 0. But taking `max_retries` and adding 1 would be super easy. I'll make that change

**Comment by JosephKav** [comment]
Yeah, I am planning to support multiple of the same notification type.
Glad to hear that you agree with my suggestion of `type`,`options`,`url_fields`,`params` then. Though I would be almost equally glad if you didn't and suggested an alternative, so thanks for coming back on this

**Comment by sinicide** [comment]
Sorry for piggybacking on this issue as I've only just started deploying this in my k8s cluster and running into a few challenges with how the config file is utilized and figure this thread might be good, if not I can create a separate issue.

My biggest challenge is that the `config.yml` file is used as both the configuration and place where you're storing status checks. So one of the things I run into is if I'm making tweaks to add/change a config I might run into an issue where a status check has modified this file.

Another is configuring the various service endpoints, I found if there's a whitespace between a service, the services following are not shown in the UI.
```
service:
  release-argus/argus:
    type: github
    url: release-argus/argus
    web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
    icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
    status:
      current_version: 0.4.1
      current_version_timestamp: "2022-05-20T02:23:56Z"
      latest_version: 0.4.1
      latest_version_timestamp: "2022-05-20T02:23:56Z"

  prusa3d/PrusaSlicer:
    type: github
    url: prusa3d/PrusaSlicer
    url_commands:
      - type: regex_submatch
        regex: version_([0-9.]+)$
    web_url: https://github.com/prusa3d/PrusaSlicer/releases/tag/version_{{ version }}
    icon: https://raw.githubusercontent.com/prusa3d/PrusaSlicer/master/resources/icons/PrusaSlicer.svg
    status:
      current_version: 2.4.2
      current_version_timestamp: "2022-05-20T04:10:05Z"
      latest_version: 2.4.2
```
For example, see the above has a whitespace between the default `release-argus/argus` service and one for `prusa3d/PrusaSlicer` when my pod is recreated I won't see the other entries in the UI until I modify my `config.yml` and restart the pod.

Anyone this is a really cool app and liking it so far.

**Comment by samcro1967** [comment]
@sinicide If you are using the published Docker container, it is at v0.4.1.  There are a couple of commits to master that are not in a new release yet that fix this issue.  Build and run you own local container to resolve the issue.  I also put some service examples in the Github discussion.  If you have developed some, it would be great if you add them as well for others to use if you are ok doing so.

**Comment by JosephKav** [comment]
> @sinicide If you are using the published Docker container, it is at v0.4.1. There are a couple of commits to master that are not in a new release yet that fix this issue #44. Build and run you own local container to resolve the issue. I also put some service examples in the Github discussion. If you have developed some, it would be great if you add them as well for others to use if you are ok doing so.

@sinicide this, but you don't have to built yourself, can just use `argus:master`

**Comment by sinicide** [comment]
@samcro1967 / @JosephKav Thanks, I was using 0.4.1, from my sample.
```
releaseargus/argus:latest
```
Was path I was using, so it should have pulled latest 0.4.1 at the time. Let me know if I should use master branch instead of latest.
I can certainly add some additional examples and will submit a PR for that when I am ready, I'm mostly using this to track 3d Printer Software updates for my home environment.

**Comment by JosephKav** [comment]
Planning on implementing this when I do https://github.com/release-argus/Argus/issues/111 + https://github.com/release-argus/Argus/issues/112. Would you recommend I change anything with the webhook config? They are all webhook options so not too sure how to split without everything being in its own group

**Comment by samcro1967** [comment]
I don't think I would change anything with the webhook config at this point.  It is already in its own section with all of the things related to it in its section.

**Comment by samcro1967** [comment]
Might make sense to move the auto approve for webhooks into the webhook config block rather than global options conf g block unless it is used for more than just user defined webhooks???

**Comment by JosephKav** [comment]
`auto_approve` acts on commands as well as webhooks

**Comment by JosephKav** [comment]
Looking at doing this now. How would you suggest I handle options like `access_token` or `allow_invalid_certs`
`access_token` is only used for the github latest version query, so could be under `latest_version`.
`allow_invalid_certs` is currently in `service` for the latest version query, and can also be under `deployed_version`, for the deployed version lookup. So if I put that in options, I'd do something like `lv_allow_invalid_certs` and `dv_allow_invalid_certs`.
(You shouldn't use `allow_invalid_certs` when you're using a github query, but just for the example)

option 1:

```yaml:
  Sonarr/Sonarr:
    options:
      semantic_versioning: false
      access_token: TOKEN
      lv_allow_invalid_certs: true
      dv_allow_invalid_certs: true
    latest_version:
      type: github
      url: release-argus/Argus
      url_commands:
        - type: regex
          regex: \"version\":\s?\"([0-9.]+)\"
          index: 1
    deployed_version:
      url: https://argus.something.io/api/v1/version
      json: version
```

option 2:
```yaml:
  Sonarr/Sonarr:
    options:
      semantic_versioning: false
    latest_version:
      type: github
      url: release-argus/Argus
      access_token: TOKEN
      allow_invalid_certs: true
      url_commands:
        - type: regex
          regex: \"version\":\s?\"([0-9.]+)\"
          index: 1
    deployed_version:
      url: https://argus.something.io/api/v1/version
      json: version
      allow_invalid_certs: true
```

**Comment by samcro1967** [comment]
I would go with option 2.  If it is not truly a global option that applies to all services, I would put it in the service block.

**Comment by samcro1967** [comment]
R U thinking of a separate section also for the dashboard options (link, icon, icon_link_to) or just putting them under the options block?

**Comment by JosephKav** [comment]
Yeah I was gonna follow your original suggestion
```yaml
  Sonarr/Sonarr:
    comment: something
    options:
      active: false
      interval: 1h
      semantic_versioning: false
    latest_version: # url
      type: url
      url: http://services.sonarr.tv/v1/releases
      allow_invalid_certs: true
      url_commands:
        - type: regex
          regex: \"version\":\s?\"([0-9.]+)\"
          index: 1
    latest_version: # github
      type: github
      url: release-argus/Argus
      access_token: TOKEN
      allow_invalid_certs: true # may just keep this incase people want to use it on machines with some kind of CA restriction?
      url_commands:
        - type: regex
          regex: \"version\":\s?\"([0-9.]+)\"
    deployed_version:
      url: https://argus.something.io/api/v1/version
      regex: [0-9.]+
      json: version
      allow_invalid_certs: true
      basic_auth:
        username: test
        password: 123
      Headers:
        - key: Authorization
          value: 'bearer hello'
    dashboard:
      auto_approve: true
      web_url: https://argus.something.io
      icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
      icon_link_to
    notify:
      - slack_id: {}
    command:
      - ['upgrade.sh', '{{service_id}}']
    webhook:
      - something: {}
```

I think that's got pretty much every possible option in the current format I'm going for

**Comment by samcro1967** [comment]
Will this be a breaking change?

**Comment by JosephKav** [comment]
It shouldn't be. I've got it converting the old style to the new and triggering a save when those conversions take place. Testing with a few different configs and go tests, it seems to work

**Comment by samcro1967** [comment]
I just tested.  It has been running about 10 mins and has not gotten beyond Starting...  My config.yml is 878 lines.  I have log level set to info.  Probably need to rerun with VERBOSE to see if I get any more info.  Guessing it has been running long enough that it should have converted by now???

Container Log
```
Switching user UID:GID to 1000:1000
Applying perms to config.yml and argus.db
Starting...
```

**Comment by JosephKav** [comment]
Could you try DEBUG too please? Ive added a print for each service as it gets converted

**Comment by samcro1967** [comment]
It seems to be getting stuck on the Argus config.

Logs
```
Switching user UID:GID to 1000:1000
Applying perms to config.yml and argus.db
Starting...
...
2022/08/10 12:24:38 DEBUG: 32/44 Argus Init
```
Argus Config
```
  Argus:
    type: github
    url: release-argus/argus
    semantic_versioning: false
    web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
    auto_approve: true
    icon: https://github.com/release-argus/Argus/raw/master/web/ui/static/favicon.svg
    icon_link_to: http://osu.argus:8111/argus/
    webhook:
      WEBHOOK_DRONE_BUILD:
        url: http://192.168.1.104:9358/hooks/drone_build?container=argus
    notify:
      MAILRISE_NOTIFICATION: {}
    deployed_version:
      url: http://localhost:8111/argus/api/v1/version
      json: version
```

**Comment by samcro1967** [comment]
Just tested and worked like a charm.

**Comment by JosephKav** [comment]
Perfect, thanks for letting me know :)

**Comment by samcro1967** [comment]
One thing I just noticed is that `active: false` is not being honored in the options block for one service I currently have it added to and set to false.

**Comment by JosephKav** [comment]
Really? `options.active: false` is working for me
```bash
❯ ./argus
INFO: Found 1 services to monitor:
  - syncthing/syncthing
INFO: Listening on 0.0.0.0:8080/
```

config.yml
```yaml
service:
  release-argus/argus:
    options:
      active: false
    latest_version:
      type: github
      url: release-argus/argus
  syncthing/syncthing:
    latest_version:
      type: github
      url: syncthing/syncthing
      use_prerelease: true
      url_commands:
        - type: regex
          regex: v(.*)
```

Is it showing in the webUI, logs, or both?
