### ISSUE TITLE
Bug: Upgrade from 0.18 to 0.19.3 results in read-only error to argus.db

### ISSUE THREAD

**Issue by thickconfusion** [release-argus/Argus#519]
**Describe the bug**
When upgrading from 0.18.0 to latest 0.19.3, I get errors about write permissions on argus.db that I didn't have with 0.18.0

**To Reproduce**
### Log errors:
```
argus  | Starting...
argus exited with code 0
argus  | INFO: Found 1 services to monitor:
argus  |   - release-argus/argus
argus  | ERROR: db (data/argus.db), removeUnknownServices: attempt to write a readonly databas
argus  | Starting...
argus  | INFO: Found 1 services to monitor:
argus  |   - release-argus/argus
argus  | ERROR: db (data/argus.db), removeUnknownServices: attempt to write a readonly databas
```
### Docker compose file:
```
Version: '3.7'

services:
  argus:
    image: releaseargus/argus:0.18.0
    container_name: argus
    volumes:
      - ./config.yml:/etc/argus/config.yml
      - ./storage/:/app/data/
    environment:
      ARGUS_UID: 1000
      ARGUS_GID: 1000
    ports:
      - 8082:8080
    healthcheck: # Optional healthcheck
      test: ["CMD", "/healthcheck", "http://localhost:8080/api/v1/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
```

### Docker host perms on the mounted file
```
$>/argus/storage$ ls -alh
total 20K
drwxr-xr-x 2 myuser myuser 4.0K Jan 17 13:11 .
drwxr-xr-x 3 myuser myuser 4.0K Jan 17 13:16 ..
-rw-r--r-- 1 myuser myuser  12K Jan 17 13:11 argus.db
```

### Container log on start for version **0.18**
```
argus  | Switching user UID:GID to 1000:1000
argus  | ---------------------------------------------------------------------
argus  | Warning - symlinking /app/config.yml to your /etc/argus/config.yml
argus  | please move your mount to /app/config.yml (everything should continue
argus  | working for now, but in future versions I may remove this symlinking)
argus  | ---------------------------------------------------------------------
argus  | Applying perms to config.yml and argus.db
argus  | Starting...
```

**Expected behavior**
When upgrading from 0..18.0 to 0.19.x, I expected it to start without any impact to/from my argus.db file.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Docker

**Smartphone (please complete the following information):**
N/A
