### ISSUE TITLE
feat: Support for filtering

### ISSUE THREAD

**Issue by KeisukeYamashita** [release-argus/Argus#527]
**Is your feature request related to a problem? Please describe.**
Currently, we use Argus to watch releases and notify Slack so that we can be aware of the release and bump our actual resources.
However, in specific dependencies, the releases occur too frequently, resulting in excessive notifications.

**Describe the solution you'd like**
Inspired by Dependabot's `ignore` option [1], adding filters based on Semantic Versioning or Regex would be great.

```yaml
service:
  grafana/grafana:
    latest_version:
      type: github
      url: grafana/grafana
      url_commands:
        - type: regex
          regex: $v([0-9.]+)$
    ignore: semvar:patch # Or any Regex that will filter {{ version }}
    dashboard:
      web_url: https://github.com/grafana/grafana/releases/tag/v{{ version }}
      icon: https://cdn.worldvectorlogo.com/logos/grafana.svg
```

**Describe alternatives you've considered**
I tried to tweak the `url_commands`' `regex` to only get the `x.y` of the GitHub release.

```yaml
service:
  grafana/grafana:
    latest_version:
      type: github
      url: grafana/grafana
      url_commands:
        - type: regex
          regex: $v([0-9]+\.[0-9]+)\..*$
    dashboard:
      web_url: https://github.com/grafana/grafana/releases/tag/v{{ version }}
      icon: https://cdn.worldvectorlogo.com/logos/grafana.svg
```

**Additional context**

[1]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#ignore
