### ISSUE TITLE
feat: Support for Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by peterbuga** [release-argus/Argus#546]
**Is your feature request related to a problem? Please describe.**
Not a dealbreaker for now but it would be nice to support [Amazon ECR Public Gallery](https://gallery.ecr.aws/) as a registry type.

example repository that it's quite known and they moved the images to ECR https://gallery.ecr.aws/gravitational/teleport-distroless

**Describe the solution you'd like**
to be able to specify in config
```
    latest_version:
      type: "github"
      url: "gravitational/teleport"
      require:
        docker:
          type: "ecr"
          image: "gravitational/teleport-distroless"
          tag: "{{ version }}"
```

**Describe alternatives you've considered**
Currently not checking if docker images are available for the specific release.

**Additional context**
`-`
