### ISSUE TITLE
bug(notify): not using env vars in params

### ISSUE THREAD

**Issue by modmew8** [release-argus/Argus#579]
**Describe the bug**
Environment variables in `notify.<id>.params` are not being replaced by the environment variables' values.

**To Reproduce**
```yaml
notify:
  mail:
    type: smtp
    url_fields:
      Username: ${MAIL_USERNAME}
      Password: ${MAIL_PASSWORD}
      Host: ${MAIL_HOST}
      Port: ${MAIL_PORT}
    params:
      FromAddress: ${MAIL_USERNAME}
      ToAddresses: ${MAIL_RECIPIENT}
```

The `url_fields` correctly get filled in with the environment variables, but the `params` do not. According to https://release-argus.io/docs/config/notify/ it should be possible to provide environment variables for `options.*`, `params.*` and `url_fields.*`.

The logins to the smtp-server succeed but sending the mail fails:

```
2025-05-16T02:30:28.333998+02:00 mail2 postfix/submissions/smtpd[6706]: NOQUEUE: reject: RCPT from unknown[172.21.0.1]: 553 5.7.1 <${MAIL_USERNAME}>: Sender address rejected: not owned by user argus@example.com; from=<${MAIL_USERNAME}> to=<${MAIL_RECIPIENT}> proto=ESMTP helo=<localhost>
```

Replacing the params environment variables with the actual values is working correctly.
