### ISSUE TITLE
Webhook Usage Question

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#58]
Working on implementing webhooks.  I am running Gitea and Drone.  Each repo in Gitea has a webhook defined that triggers a build in Drone.

The webhook looks like `http://osu.drone:3070/hook?secret=<redacted>`

I have never used webhooks before so I am guessing I am just doing something wrong.  When I click approve, it tries three times and fails.

**Logs**
```
INFO: wsServiceAction (192.168.1.227), CaddyRealIP Release approved - "GITEA_WEBHOOK" WebHook
INFO: GITEA_WEBHOOK (CaddyRealIP), (200) WebHook received
INFO: wsServiceAction (192.168.1.227), CaddyRealIP Release approved - "ALL UNSENT/FAILED" WebHook
```
**Global Block Webook Definition**
```
webhook:
  GITEA_WEBHOOK:
    type: web
    url: http://osu.drone:3070/hook?secret=
    secret: SECRET
    DesiredStatusCode: 201
    delay: 0s
    max_tries: 3
    silent_fails: false
```

**CaddyRealIP Service Definition**
```
  CaddyRealIP:
    type: url
    url: https://github.com/kirsch33/realip/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/kirsch33/realip/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    gotify:
      GOTIFY_NOTIFICATION: {}
    webhook:
      GITEA_WEBHOOK:
        secret: '<redacted>'
    deployed_version:
      url: http://osu.logs:8069/caddy2/current_version.txt
      regex: realip\s?(v[0-9.]+)
```
