### ISSUE TITLE
bug(deployed_verison): env vars not working for deployed_version.basic_auth.password

### ISSUE THREAD

**Issue by modmew8** [release-argus/Argus#591]
**Describe the bug**
Environment variables in `service.service-name.deployed_version.basic_auth.password` are not being replaced by the environment variables' values.

**To Reproduce**
```yaml
service:
  argus:
    latest_version:
      type: github
      url: release-argus/argus
    deployed_version:
      type: url
      method: GET
      url: http://localhost:8080/api/v1/version
      json: version
      basic_auth:
        username: my_user
        password: ${ARGUS_PASSWORD}
    dashboard:
      icon: https://raw.githubusercontent.com/release-argus/Argus/master/web/ui/react-app/public/favicon.svg
      web_url: https://github.com/release-argus/Argus/blob/master/CHANGELOG.md
```

The password variable is the same one used for the docker compose environment:

```yaml
services:
  app:
    image: releaseargus/argus:0.26.3
...
    environment:
      - ARGUS_WEB_BASIC_AUTH_USERNAME=my_user
      - ARGUS_WEB_BASIC_AUTH_PASSWORD=${ARGUS_PASSWORD}
...
```

But the deployed_version check fails with 401 permission denied. Replacing the password on the webgui with the actual password and pressing test would work, so I assume the replacement does not take place.

**Comment by modmew8** [comment]
Hey @JosephKav,

thanks for checking, you are completely right - it was an issue with my Docker/env setup as I wrongly assumed the `.env` is already assigned to the running container. Terribly sorry for raising this bug issue for my mistake.

For others reading this issue in the future, the following minimal docker compose setup works just fine:

```yaml
##compose.yaml
services:
  app:
    image: releaseargus/argus:0.26.3
    container_name: argus
    ports:
      - 127.0.0.1:10380:8080/tcp
    environment:
      - ARGUS_UID=10380
      - ARGUS_GID=10380
      - ARGUS_WEB_BASIC_AUTH_USERNAME=${ARGUS_USERNAME}
      - ARGUS_WEB_BASIC_AUTH_PASSWORD=${ARGUS_PASSWORD}
      - ARGUS_USERNAME=${ARGUS_USERNAME}
      - ARGUS_PASSWORD=${ARGUS_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yml
      - ./data:/app/data/

```

```yaml
##./config.yaml
service:
  Test:
    latest_version:
      type: github
      url: release-argus/Argus
    deployed_version:
      type: url
      method: GET
      url: http://localhost:8080/api/v1/version
      basic_auth:
        username: ${ARGUS_USERNAME}
        password: ${ARGUS_PASSWORD}
      json: version

```

```ini
##./.env
ARGUS_USERNAME=someuser
ARGUS_PASSWORD=somepassword

```
