### ISSUE TITLE
Notify config removed after config.xml is updated

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#75]
I noticed that since updating to the latest master commit on Fri., the notify config for services is removed after a scan is complete and config.xml is updated.  Below is a before and after.  The notification does work on the first run, but 30 mins later on the next run and all those thereafter, no notifications are sent.

**Before starting Argus**
```
  Caddy:
    type: url
    url: https://github.com/caddyserver/caddy/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/caddyserver/caddy/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    notify:
      MAILRISE_NOTIFICATION: {}
    webhook:
      WEBHOOK_DRONE_BUILD:
        url: http://192.168.1.104:9357/hooks/drone-build?container=caddy
    deployed_version:
      url: http://osu.logs:8069/caddy2/current_version.txt
      regex: caddy.adapters.caddyfile\s?(v[0-9.]+)
```

**After Argus starts, scan all services, and updates config.xml**
```
  Caddy:
    type: url
    url: https://github.com/caddyserver/caddy/tags
    semantic_versioning: false
    url_commands:
      - type: regex
        regex: releases\/tag\/(v[0-9.]+)
    web_url: https://github.com/caddyserver/caddy/releases
    icon: https://raw.githubusercontent.com/walkxhub/dashboard-icons/master/svg/caddy.svg
    notify:
    webhook:
      WEBHOOK_DRONE_BUILD:
        url: http://192.168.1.104:9357/hooks/drone-build?container=caddy
    deployed_version:
      url: http://osu.logs:8069/caddy2/current_version.txt
      regex: caddy.adapters.caddyfile\s?(v[0-9.]+)
    status:
      deployed_version: v2.5.1
      deployed_version_timestamp: "2022-05-19T11:20:52Z"
      latest_version: v2.5.1
      latest_version_timestamp: "2022-05-19T12:26:00Z"
```
