### ISSUE TITLE
feat: Clarification on how to properly use new (0.5.1) Shoutrrr notifications

### ISSUE THREAD

**Issue by jrhbcn** [release-argus/Argus#82]
Hello,

I am trying to use the new shoutrrr notification to send telegram messages. I have created an entry in:
```
defaults:
  notify:
    telegram_updates:
      type: telegram
      url_fields:
        Token: TOKEN_FROM_BOTFATHER
      params:
        Chats: 'chat_id'
```

- Do I need now to add a "notify:" entry for each service for them to notify on new releases? I haven't and I don't receive any notifications. (makes sense as I only want to receive notifications on certain services not all).
- If I add an entry "notify: telegram_updates:" in a service it complains that the type is needed, if I then add the type it asks for token, so it seems I need to repeat the config in defaults. 

Is this the expected behaviour? Regards,

**Comment by JosephKav** [comment]
So first thing, it's gotta be `defaults.notify.TYPE`, where TYPE would be telegram in this case.
If you want to share a telegram between multiple Services, you should make it under `notify.any_name`, and then for each service that wants to use it, give them that `notify.any_name` along with any vars that you want to override for that service (could be none).
You can still use the Defaults, but some of the vars will need to be in the `notify`/`service.X.notify`

**Comment by jrhbcn** [comment]
I am sorry @JosephKav but I am already lost 😞 I am following the docs in release-argus.io so when you say:

> So first thing, it's gotta be `defaults.notify.TYPE`, where TYPE would be telegram in this case. 

You mean `defaults.notify.ID.type`? so, is my code above correct then? or do I need to move the `type: telegram` somewhere else in the yaml file?

> If you want to share a telegram between multiple Services, you should make it under `notify.any_name`, 

Again, lost, sorry!! you mean inside the `defaults` as before?

> and then for each service that wants to use it, give them that `notify.any_name` along with any vars that you want to override for that service (could be none). You can still use the Defaults, but some of the vars will need to be in the `notify`/`service.X.notify`

That's what I find strange, it we setup a notification in defaults, shouldn't it be referenced only by ID in the service.X:notify?

**Comment by JosephKav** [comment]
> You mean `defaults.notify.ID.type`? so, is my code above correct then? or do I need to move the `type: telegram` somewhere else in the yaml file?

`defaults.notify.telegram` contains defaults for all telegram notifiers that you use. You can only make 1 set of defaults for each type, e.g. slack/discord/telegram. You can't make a default specific to a named telegram notifier (so type means nothing inside defaults as the name **is** the type)

> Again, lost, sorry!! you mean inside the `defaults` as before?

```yaml
notify:
  telegram_updates:
    type: telegram
    url_fields:
      token: TOKEN_FROM_BOTFATHER
    params:
      chats: 'chat_id'
```


> That's what I find strange, it we setup a notification in defaults, shouldn't it be referenced only by ID in the service.X:notify?

They can be, but not if you set it up in defaults. If you do the YAML I posted, then you can do
```yaml
service:
  Something:
    notify:
      telegram_updates: {}
```

**Comment by jrhbcn** [comment]
I have exactly that in my config and I get:

```
ERROR: Config could not be parsed successfully.
service:
  Argus:
    notify:
      telegram_updates:
        type: <required> e.g. 'slack', see the docs for possible types - https://release-argus.io/docs/config/notify
        ^ unknown service ""

```
ERROR: Config could not be parsed successfully.

**Comment by JosephKav** [comment]
What are your defaults and notify?

**Comment by jrhbcn** [comment]
I have got this in defaults:

```
notify:
  telegram_updates:
    type: telegram
    url_fields:
      token: TOKEN_FROM_BOTFATHER
    params:
      chats: 'chat_id'
```

And this in argus service:

```
    notify:
      telegram_updates: {}
```

**Comment by JosephKav** [comment]
As I've said a few times here, you can't have defaults for a specific notify, only for types of notify. https://release-argus.io/docs/config/defaults/#notify-portion

```yaml
notify:
  telegram:
    type: telegram
    url_fields:
      token: TOKEN
    params:
      chats: ID
service:
  release-argus/argus:
    type: github
    url: release-argus/argus
    notify:
      telegram: {}
```
^ works
