### ISSUE TITLE
Getting up and running / installation documentation

### ISSUE THREAD

**Issue by quantumzedno** [release-argus/Argus#84]
Hi there,

I am very interested in this project and have been trying to set up a test vm with it for awhile but i've been struggling to get it up and running with the getting started documentation and was hoping to get some assistance/ request (or even help create) better setup documentation once I understand how to get going:

what i've done so far:

downloaded latest binary Argus-0.6.0.linux-amd64

transferred binary to centos 8 vm via scp

gave the binary execute permissions via chmod

ran ./Argus-0.6.0.linux-amd64 -help

created a /home/argus/argus directory structure and moved the binary to /home/argus/argus/Argus-0.6.0.linux-amd64

created a config.yml at /home/argus/argus/config.yml

```
added the following to the config.yml file just for a test:

settings:
  log:
    level: INFO           # Log level, DEBUG/VERBOSE/INFO/WARNING/ERROR
    timestamps: false     # Log with timestamps
  web:
    listen_host: 172.29.2.128  # IP address to listen on
    listen_port: 8080     # Port to listen on
    route_prefix: /       # Web route prefix, e.g. /demo means http://IP:PORT/demo to access
    cert_file: ''         # HTTPS Cert path, e.g. `cert.pem`
    pkey_file: ''         # HTTPS PrivKey path, e.g. `privkey.pem`

service:
  adnanh/webhook:
    type: github
    url: adnanh/webhook
    web_url: https://github.com/adnanh/webhook/releases/{{ version }}
    regex_content: webhook-linux-amd64\.tar\.gz
    icon: https://raw.githubusercontent.com/adnanh/webhook/development/docs/logo/logo-128x128.png
```

created a systemd service file at /etc/systemd/system/argus.service
```

[Unit]
Description=Argus Server
Documentation=https://release-argus.io/docs
After=network-online.target

[Service]
User=argus
Restart=on-failure
ExecStart=/home/argus/argus \
  -config.file=/home/argus/argus/config.yml

[Install]
WantedBy=multi-user.target
```

I'm not sure what else, but i feel like i'm definitely missing something....
 i cant hit the web ui at the boxes ip address (172.29.2.128:8080)
also tried disabling firewall and se linux so it's neither of those
