### ISSUE TITLE
WebUI Suggestion - Add Service Link

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#86]
I know the intent of this is not to be a dashboard replacement, but I am finding I am going back and forth a lot between Argus and my app dashboard to verify updates after running webhooks.  To not change the existing card view, wondering if you would you entertain making the icon a link we can define that would open up the service in a new window?

**Comment by JosephKav** [comment]
Good idea. Think this is as close to a dashboard as I'll go.
So I have this implemented, but am unsure of the naming of the var for this link
Ideally, I'd like to be able to support
```yaml
service:
  argus:
    icon: https://example.com/something.png
```
and
```yaml
service:
  argus:
    icon:
      url: https://example.com/something.png
      link_to: https://you.site
```

but I'm not too sure how to implement that nicely/cleanly. I think I'd need to duplicate each Service, one with each type :/.
So I've got it setup currently as 
```yaml
service:
  argus:
    icon: https://example.com/something.png
    icon_link_to: https://you.site
```
If you can think of any nicer names than `icon_link_to`, please let me know 😄.
Did think `icon_link`, but that could be interpreted as just another format for `icon`. It's not really clear that it's the link the icon would take you to.
