### ISSUE TITLE
Disable a Service in `config.yml`

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#87]
Disable a service without removing it from the `config.yml` entirely
```yaml
service:
  argus:
    active: false
    type: github
    url: release-argus/argus
```

Maybe another option could be adding a service option called active (or something more creative) with a value of true or false so that it is only added to the dashboard and checks if true.  If not present, defaults to true.  That way it can be kept in the config file at all times and set to false.

_Originally posted by @samcro1967 in https://github.com/release-argus/Argus/issues/85#issuecomment-1156439023_
