### ISSUE TITLE
comments in `config.yml` with `comment` var(s)

### ISSUE THREAD

**Issue by JosephKav** [release-argus/Argus#89]
```yaml
service:
  something:
    comment: whatever you want
```
---

Maybe a quick alternative to comments could be to just add it to the yaml config and do nothing with it.

```yaml
  Argus:
    comment:  This is a test comment.
    type: github
    url: release-argus/argus
```

_Originally posted by @samcro1967 in https://github.com/release-argus/Argus/issues/85#issuecomment-1156439023_
