### ISSUE TITLE
feat: pass version to webhook or command

### ISSUE THREAD

**Issue by TheFrazer** [release-argus/Argus#97]
I tried using `{{ version }}` in a webhook request or as a command parameter. Both didn't get expended.
Is it possible to pass the version in one or both of these?

**Comment by JosephKav** [comment]
version = 1.2.3

You're wanting
```yaml
webhook:
  name:
    url: https://example.com/{{ version }}
```
to use `https://example.com/1.2.3`

and 
```yaml
command:
  - ["something.sh", "{{ version }}"]
```
should do `something.sh 1.2.3`
